### ISSUE TITLE
Trying to migrate the DB

### ISSUE THREAD

**Issue by binte** [WeblateOrg/docker#1006]
Hi! 

I am trying to migrate the database from one instance of weblate that has been deployed via docker, and I am struggling to do that. 

When I generate a dump, it seems not to contain any data. So, I connected to the DB with the _postgres_ user, and again, no data was there: just what seems to be 3 standard tables: _template0_, _template1_ and _postgres_. 

When I try to connect to the DB with the _weblate_ user, I get the following error message:

_psql: FATAL:  role "weblate" does not exist_

Any ideas on how can we perform this task?

**Comment by nijel** [comment]
Maybe you are connecting to a wrong server? You can use `weblate dbshell` to connect to server configured in Weblate settings

**Comment by binte** [comment]
I tried that, and got this error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/weblate/runner.py", line 37, in main
    report_error(error)
  File "/usr/local/lib/python2.7/dist-packages/weblate/utils/errors.py", line 61, in report_error
    if not skip_sentry and settings.SENTRY_DSN:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings

```


Do I need to pass in some arguments to the command?

**Comment by nijel** [comment]
Usually not, see https://docs.weblate.org/en/latest/admin/management.html

**Comment by binte** [comment]
I could not find the command you mentioned before, however I find something that looks very useful. I tried to run 

> weblate dumpuserdata dump.json

But again, I am getting an error. Very similar to the previous error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/weblate/runner.py", line 37, in main
    report_error(error)
  File "/usr/local/lib/python2.7/dist-packages/weblate/utils/errors.py", line 61, in report_error
    if not skip_sentry and settings.SENTRY_DSN:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings

```

**Comment by nijel** [comment]
I have no clue what is your setup and how do you execute Weblate. You might need to pass [DJANGO_SETTINGS_MODULE](https://docs.djangoproject.com/en/3.1/topics/settings/#envvar-DJANGO_SETTINGS_MODULE) if you are using non-standard location for settings.

**Comment by binte** [comment]
Hi @nijel,

Thank you for the hint, I was indeed checking in the wrong place. I was able to generate the dump by connecting to the container running postgres, and executing the following command:

`pg_dumpall -v --host=localhost --username=weblate -f dump.sql`

Then I executed the generated script on the AKS pod with:

`psql -f dump.sql -U postgres`

However, only the projects were created: neither user data nor translations were created on the new weblate instance! Shouldn't that be the case?

**Comment by nijel** [comment]
Maybe the import didn't work for some reason? Did you check the output?

**Comment by binte** [comment]
I haven't, because it seemed alright at first glance, only noticed the issue later. I have executed the dump again, and this time data was indeed created, but there are some issues:

- Instead of English US, English UK, Spanish and Spanish American, in the new instance I have Chiga, Chipewyan, Kashubian and Kurdish
- No user data was created

Any advice here? Maybe I can delete all the data and retry to run the dump. But how can I do that?

**Comment by nijel** [comment]
When importing a database dump, you should start with a blank database, use [DROP DATABASE](https://www.postgresql.org/docs/current/sql-dropdatabase.html) / [CREATE DATABASE](https://www.postgresql.org/docs/current/sql-createdatabase.html) for that. When importing into existing Weblate database, your data will only partially imported (that should be visible in the postgres import log) and will be messed up (as you've observed in the languages).
