### ISSUE TITLE
Removing EXPOSE 4443 prevents HTTPS?

### ISSUE THREAD

**Issue by stevevg** [WeblateOrg/docker#1019]
I'm trying to setup a weblate instance, using docker, with HTTPS and my own valid SSL certificate.
However, following the [documentation](https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=https#docker-container-with-https-support), I was not able to access weblate.

I saw, in issue #863, that the EXPOSE 4443 port on Dockerfile was removed. Now, where is the HTTPS server listening on the weblate image?

Is there something I'm missing, or is the documentation out of date?

**I already tried**

* Setting in environment file:
```
WEBLATE_ENABLE_HTTPS=1
WEBLATE_SECURE_SSL_REDIRECT=1
```

* Publishing port `443:8080` in docker-compose.override.yml (Chrome replies with a ERR_SSL_PROTOCOL_ERROR message)

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.

**Expected behavior**

Would like to connect to weblate using my own certificate

**Comment by nijel** [comment]
The port 4443 is still there, it's just not listed in EXPOSE. It works as documented in https://docs.weblate.org/en/latest/admin/install/docker.html#using-own-ssl-certificates

**Comment by stevevg** [comment]
Ok, I had a misconfiguration on certificates. I was able to fix it. Sorry.
