### ISSUE TITLE
error: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/docker#1025]
**Describe the issue**

I get an error when starting weblate.

**To Reproduce the issue**

1) Launch weblate in the docker
2) Errors appear before full boot

**Expected behavior**

No errors
**Additional context**
[Sentry log](https://sentry.io/share/issue/84716fa1f4f742b9a79206acb91ac6da/#exception)

**Comment by nijel** [comment]
Errors? Does that happen multiple times? The schedule file cleanup should be triggered just once...

**Comment by tomkolp** [comment]
![image](https://user-images.githubusercontent.com/39633242/112988006-9f940580-9163-11eb-96b9-85d441c7ef84.png)

**Comment by nijel** [comment]
So this is once for each container startup?

**Comment by tomkolp** [comment]
> So this is once for each container startup?

Yes

**Comment by nijel** [comment]
This error seems to happen on concurrent access to the file (see https://stackoverflow.com/q/52381091/225718). This startup check is not parallel at all, so there should be nothing else accessing the file. Do you happen to run more Weblate containers on the same data dir?
