### ISSUE TITLE
LDAP connection issue

### ISSUE THREAD

**Issue by aadittmk** [WeblateOrg/docker#1026]
**Describe the issue**

Unable to connect to LDAP server even after configuring docker-compose.override.yml with appropriate needed settings.

Error logs read:
```Caught LDAPError while authenticating xxx: SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'})```

**I already tried**

1. Configured docker-compose.override.yml with multiple combinations of possible settings
2. Tried connected to the LDAP server via telnet, this was okay and had no issues. The port our LDAP server uses was added to the ports needed to forward. (attached screenshot below)

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

LDAP server hosted on a private network, cannot share access.

**Expected behavior**

Authorization via LDAP

**Screenshots**

docker-compose.override.yml file
![image](https://user-images.githubusercontent.com/35492632/112966453-e1bf4600-9167-11eb-8adb-8367f448e733.png)

Docker log with error mentioned
![image](https://user-images.githubusercontent.com/35492632/112966741-20ed9700-9168-11eb-81c1-fe8c31c19fe6.png)

**Exception traceback**

None

**Additional context**

None

**Comment by nijel** [comment]
The port mappings in Docker will certainly not help in reaching outside LDAP server. Does your server listed on SSL sockets? Maybe you should use `ldap:` instead of `ldaps:`?

**Comment by aadittmk** [comment]
I removed the port mappings and tried - no success. Yes, our server listens on SSL sockets.

Running nmap shows these ports.

![image](https://user-images.githubusercontent.com/35492632/113163137-80799e80-925d-11eb-85e4-a310df0ed6de.png)

Any chance these ports have to be configured in the docker-compose.override file?

**Comment by nijel** [comment]
Maybe it's an issue with SSL certificate then.

**Comment by aadittmk** [comment]
Would the SSL certificate be an issue even if we use ldap instead of ldapssl? 
I tried switching it to plain ldap and I couldn't get it to work either

**Comment by nijel** [comment]
Do you get same error in that case?

**Comment by aadittmk** [comment]
This issue is fixed, it was a configuration error on our end.
This is what worked for us:
![image](https://user-images.githubusercontent.com/35492632/113270749-7310f280-92f7-11eb-8b47-f252a7475cc9.png)

Thank you!
