### ISSUE TITLE
E-mail SMTP issue

### ISSUE THREAD

**Issue by aadittmk** [WeblateOrg/docker#1027]
**Describe the issue**

Cannot send e-mails even post configuring weblate-related e-mail settings, smtp server is being used in other instances and is working fine.

A crucial system check is also failing.

Error logs read:
```Cannot send e-mail (SMTP AUTH extension not supported by server.), please check EMAIL_* settings.```

**I already tried**

1. Configured docker-compose.override.yml with multiple combinations of possible settings
2. The e-mail server is working as intended while used elsewhere
3. Docker documentation suggests enabling EMAIL_USE_TLS
>In case you get error about not supported authentication (for example SMTP AUTH extension not supported by server), it is most likely caused by using insecure connection and server refuses to authenticate this way. Try enabling EMAIL_USE_TLS in such case

Source: https://docs.weblate.org/en/weblate-4.5.1/admin/install.html#out-mail 
Attached screenshot below with setting enabled

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

SMTP server hosted on a private network, cannot share access.

**Expected behavior**

Authorization via LDAP

**Screenshots**

docker-compose.override.yml file
![image](https://user-images.githubusercontent.com/35492632/112966453-e1bf4600-9167-11eb-8adb-8367f448e733.png)

Docker log with error mentioned
![image](https://user-images.githubusercontent.com/35492632/112967923-652d6700-9169-11eb-92ba-2d132b3b743d.png)

**Exception traceback**

None

**Additional context**

None

**Comment by nijel** [comment]
Maybe your server doesn't support TLS? Try using different port and SSL. Looking into mail server logs might tell you more.
