### ISSUE TITLE
Invalid HTTP_HOST header: ''

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/docker#104]
I keep getting this email from weblate running in docker.   Any clue what is causing this or how to fix it?
Seems to happen at random times,   maybe once or twice per hour.

subject:  [Weblate] ERROR (EXTERNAL IP): Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.

> Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
> 
> Report at / Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
> 
> Request Method: GET Request URL: http:/// Django Version: 2.1.3 Python Executable: /usr/bin/uwsgi-core Python Version: 3.6.7 Python Path: ['/usr/local/lib/python3.6/dist-packages/', ‘.’, '', ‘/usr/lib/python36.zip’, ‘/usr/lib/python3.6’, ‘/usr/lib/python3.6/lib-dynload’, ‘/usr/local/lib/python3.6/dist-packages’, ‘/usr/lib/python3/dist-packages’, ‘/’] Server time: Ср, 12 Дек 2018 09:52:23 -0600 Installed Applications: ['django.contrib.auth',
> 
> 'django.contrib.contenttypes',
> 'django.contrib.sessions',
> 'django.contrib.sites',
> 'django.contrib.messages',
> 'django.contrib.staticfiles',
> 'django.contrib.admin.apps.SimpleAdminConfig',
> 'django.contrib.admindocs',
> 'django.contrib.sitemaps',
> 'social_django',
> 'crispy_forms',
> 'compressor',
> 'rest_framework',
> 'rest_framework.authtoken',
> 'weblate.addons',
> 'weblate.auth',
> 'weblate.checks',
> 'weblate.formats',
> 'weblate.machinery',
> 'weblate.trans',
> 'weblate.lang',
> 'weblate.langdata',
> 'weblate.memory',
> 'weblate.screenshots',
> 'weblate.accounts',
> 'weblate.utils',
> 'weblate.vcs',
> 'weblate.wladmin',
> 'weblate',
> 'weblate.gitexport']
> Installed Middleware: ['weblate.middleware.ProxyMiddleware',
> 
> 'django.middleware.security.SecurityMiddleware',
> 'django.contrib.sessions.middleware.SessionMiddleware',
> 'django.middleware.common.CommonMiddleware',
> 'django.middleware.locale.LocaleMiddleware',
> 'django.middleware.csrf.CsrfViewMiddleware',
> 'weblate.accounts.middleware.AuthenticationMiddleware',
> 'django.contrib.messages.middleware.MessageMiddleware',
> 'django.middleware.clickjacking.XFrameOptionsMiddleware',
> 'social_django.middleware.SocialAuthExceptionMiddleware',
> 'weblate.accounts.middleware.RequireLoginMiddleware',
> 'weblate.middleware.SecurityMiddleware']
> Request information: USER: [unable to retrieve the current user]
> 
> GET: No GET data
> 
> POST: No POST data
> 
> FILES: No FILES data
> 
> COOKIES: No cookie data

**Comment by nijel** [comment]
Are you running some reverse proxy in front? Most likely it's not properly passing `Host:` HTTP header.

**Comment by paulpach** [comment]
I think I figured this out.   I am deploying your weblate docker image in kubernetes  and I needed to use an ingress service to expose it.

**Comment by mleneveut** [comment]
@paulpach Can you help us running Weblate in Kubernetes plz ? https://github.com/WeblateOrg/weblate/issues/1205
