### ISSUE TITLE
Weblate ignores WEBLATE_CONTACT_FORM

### ISSUE THREAD

**Issue by Somebodyisnobody** [WeblateOrg/docker#1044]
**Describe the issue**
When someone tries sending a message via contact form I get an error instead as weblate tries to send the mail from another e-mail address (the one entered in the contact form). This error is sent to me via email by django.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [ X ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.
- [ X ] I've explecitely set `WEBLATE_CONTACT_FORM="reply-to"` in my environments file (according to https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=contact#envvar-WEBLATE_CONTACT_FORM) and migrated with `docker-compose stop && docker-compose up -d`
- [ X ] also tried it with `...=reply-to`

**To Reproduce the issue**

Not sure if reproducable but i've set following settings:
```
# See Weblate documentation for detailed description:
# https://docs.weblate.org/en/latest/admin/deployments.html#docker

# Weblate setup
WEBLATE_DEBUG=0
WEBLATE_LOGLEVEL=INFO
WEBLATE_SITE_TITLE=Weblate
WEBLATE_ADMIN_NAME=Administrator
WEBLATE_SITE_DOMAIN=<domain>
WEBLATE_ADMIN_EMAIL=<address1>
WEBLATE_ADMIN_PASSWORD=<pass>
WEBLATE_SERVER_EMAIL=<address2>
WEBLATE_DEFAULT_FROM_EMAIL=<address2>
# https://docs.weblate.org/en/latest/admin/install/docker.html?highlight=contact#envvar-WEBLATE_CONTACT_FORM
WEBLATE_CONTACT_FORM="reply-to"
WEBLATE_ALLOWED_HOSTS=<domain>
WEBLATE_REGISTRATION_OPEN=0
WEBLATE_HIDE_VERSION=1

## Github
WEBLATE_GITHUB_USERNAME=Somebodyisnobody
WEBLATE_GITHUB_TOKEN=<token>
WEBLATE_DEFAULT_COMMITER_EMAIL=<address2>
WEBLATE_DEFAULT_COMMITER_NAME=<domain>

# Extra
WEBLATE_TIME_ZONE=Europe/Berlin
#WEBLATE_MT_GOOGLE_KEY=
#WEBLATE_SOCIAL_AUTH_GITHUB_KEY=
#WEBLATE_SOCIAL_AUTH_GITHUB_SECRET=
#WEBLATE_SOCIAL_AUTH_BITBUCKET_KEY=
#WEBLATE_SOCIAL_AUTH_BITBUCKET_SECRET=
#WEBLATE_SOCIAL_AUTH_FACEBOOK_KEY=
#WEBLATE_SOCIAL_AUTH_FACEBOOK_SECRET=
#WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=
#WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=

#WEBLATE_OFFLOAD_INDEXING=1
#WEBLATE_GOOGLE_ANALYTICS_ID=
#WEBLATE_ENABLE_HTTPS=1
WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR
#WEBLATE_REQUIRE_LOGIN=1

# LDAP Auth
#WEBLATE_AUTH_LDAP_SERVER_URI=ldap://ldap.example.org
#WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE=uid=%(user)s,ou=People,dc=example,dc=net
#WEBLATE_AUTH_LDAP_USER_ATTR_MAP=first_name:name,email:mail

# PostgreSQL setup
POSTGRES_PASSWORD=weblate
POSTGRES_USER=weblate
POSTGRES_DATABASE=weblate
POSTGRES_HOST=database
POSTGRES_PORT=

# Cache setup
# https://docs.weblate.org/en/latest/admin/install.html#production-cache
REDIS_HOST=cache
REDIS_PORT=6379

# Mail server, the server has to listen on port 587 and understand TLS
WEBLATE_EMAIL_HOST=smtp.domain.com
# Do NOT use quotes here
WEBLATE_EMAIL_HOST_USER=<address2>
# Do NOT use quotes here
WEBLATE_EMAIL_HOST_PASSWORD=<pass>

# GitLab lab setup
# WEBLATE_GITLAB_USERNAME=
# WEBLATE_GITLAB_HOST=
# WEBLATE_GITLAB_TOKEN=
```

**Expected behavior**
Django should send the mail with the submitted address as reply-to.
- https://github.com/WeblateOrg/weblate/blob/a7667d45ca3f10bc5fee4d1104986c2f2e2f4252/weblate/settings_docker.py#L1217
- https://docs.weblate.org/en/latest/admin/config.html#std-setting-CONTACT_FORM

**Screenshots**
-

**Exception traceback**
```
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/views.py", line 510, in contact
    settings.ADMINS_CONTACT,
  File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/views.py", line 226, in mail_admins_contact
    mail.send(fail_silently=False)
  File "/usr/local/lib/python3.7/dist-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.7/dist-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.7/smtplib.py", line 867, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
```

**Additional context**
- SMTP-Server sent: You are not authorized to send mail from: <contact-form-entered-address>'
- Running behind a reverse proxy

**Comment by nijel** [comment]
Are you running 4.6 where this setting was introduced? It was not yet released, but you can get it as bleeding tag

**Comment by Somebodyisnobody** [comment]
I pulled via `git clone https://github.com/WeblateOrg/docker-compose.git weblate-docker` yesterday so I assume to have the latest version. You're right it's 4.5.3. But how this was solved before?

**Comment by nijel** [comment]
It was not solved before

**Comment by Somebodyisnobody** [comment]
Okay, I thought the contact form was released in a working state 😉. Then i'll close this and wait for 4.6.

**Comment by nijel** [comment]
It was working for many setups, it just depends on how your mailserver is configured.

**Comment by Somebodyisnobody** [comment]
of course I cannot and won't send mails with a mail address in the from header that belongs to a foregin domain/infrastructure. That's why I'ld like to use the reply-to header.
