### ISSUE TITLE
Missing addons

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/docker#106]
I have weblate 3.3  running in docker.  

I am looking at the addons page, and I only see:
* Language Consistency
* Statistics Generator
* Customize Gettext Output

How come I don't see other addons?   Is there something I have to do to enable msgmerge addon?

**Comment by nijel** [comment]
Only compatible addons are listed, so probably others are not or their dependencies are not met. For example the msgmerge addon needs gettext tools installed, what is currently not true for the Docker container.

**Comment by nijel** [comment]
...hmm actually it is installed. So most likely your component setup is not compatible with it. Do you have set base file for new translations?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by paulpach** [comment]
Is a release coming out soon?   we would really love to get this fix deployed.

**Comment by nijel** [comment]
It should be out next week, see https://github.com/WeblateOrg/weblate/milestone/25.
