### ISSUE TITLE
Docker Image Upgrade failing

### ISSUE THREAD

**Issue by rvalle** [WeblateOrg/docker#1066]
**Describe the issue**

According to the documentation: "The official Docker image (see Installing using Docker) has all upgrade steps integrated. There are no manual step besides pulling latest version." However pulling the latest version (4.6.1) in order to update a fairly recent one (4.5.3) or about 1 month old results in missing projects, users, etc.

Describe the steps you tried to solve the problem yourself.

- [X] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

1. Install weblate docker 4.5.3 
2. put projects, users, repos, etc.
3. pull the latest image (now it is 4.6.1)
4. start weblate docker again

**Expected behavior**

All Data, projects and repos should be there

**Additional context**

**Comment by rvalle** [comment]
I am suspicious of this, quite persistent warning:
```
Handled exception: ValueError: Couldn't load 'Argon2PasswordHasher' algorithm library: No module named 'argon2'
```

**Comment by nijel** [comment]
The argon2 library is listed in the requirements:

https://github.com/WeblateOrg/docker/blob/f851b0dff8c8f70bc96eeaff4e335d6badb973ab/requirements.txt#L3

What architecture do you use?

**Comment by rvalle** [comment]
I am using amd64

That is very strange.... 

is this image separating code/data properly? our docker servers back up all data volumes.

Could it be that there is code in data volumes? 

I will review and see if I find out what could be going on.

**Comment by rvalle** [comment]
Is weblate performing automated backup operations? perhaps automated restore on upgrade?

Our docker volumes are backed up/ restored by 3rd party software. could that be the case?

**Comment by rvalle** [comment]
Ok, I can see our PSQL backup failed. So this does not seem to be related to the upgrade in itself.

I will proceed to restore from the data/backup directory.
