### ISSUE TITLE
Redis configuration missing for weblate profile

### ISSUE THREAD

**Issue by Anderen2** [WeblateOrg/docker#108]
It seems like the Redis environmental configuration is not written to /etc/profile.d/weblate.sh. 
I assume "REDIS_" should be included in the list for grep in https://github.com/WeblateOrg/docker/blob/master/start#L76

I'm unsure what effect this has in the latest release, however with 3.1.1-5 this causes the cronjobs to fail.

**Comment by nijel** [comment]
The last releases do not use cron by default, that's why it's probably not noticed :-).

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/docker/pull/109
