### ISSUE TITLE
Restore container volumes 

### ISSUE THREAD

**Issue by jmanaks1** [WeblateOrg/docker#1101]
Hello Team,

We have currently installed Weblate version 4.5.3  and want to upgrade it to latest version 4.6.2. So we have copied all three container's volumes directory (mentioned below) with metadata_db as  a backup & trying to restore it on another machine. 

/var/lib/docker/volumes/weblate-docker_weblate-data
/var/lib/docker/volumes/weblate-docker_postgres-data
/var/lib/docker/volumes/weblate-docker_redis-data
metadata_db

So Could you please suggest how to restore those backup directories as a volume for new weblate containers?

Thank you

**Comment by nijel** [comment]
You can let Docker create the volumes and then copy just the content.
