### ISSUE TITLE
Update social-auth-core requirement to use version 3.0.0

### ISSUE THREAD

**Issue by skvalex** [WeblateOrg/docker#112]
New release 3.0.0 of python-social-auth/social-core has come out recently. It has important change to use Google Sign In API instead of Google+ which is going to be shut down very soon: https://github.com/python-social-auth/social-core/pull/301

After this update, it might be needed to update the docs as well: https://docs.weblate.org/en/weblate-3.3/admin/auth.html#google-oauth2

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
