### ISSUE TITLE
Add 3.4 tag to dockerhub

### ISSUE THREAD

**Issue by msheiny** [WeblateOrg/docker#114]
At time of this writing ~19 UTC Jan 22nd 2019 - there is no `3.4.x` tag for the 3.4 train of the weblate docker image. This is currently pushed as `latest` but for long-term version control this is not ideal for us to target `latest` tag. I realize you are in the midst of a release process so apologies if this is a redundant ticket and this tag process is already underway.

**Comment by msheiny** [comment]
Nevermind its there now! at `3.4-1` ! thannnnnnks

**Comment by nijel** [comment]
Yes, it takes time as I wait for images to build and test before tagging them.
