### ISSUE TITLE
[Bug] weblate.E002	on Docker Deployment

### ISSUE THREAD

**Issue by ShadowXVII** [WeblateOrg/docker#116]
I get the following error reported in the Admin interface as a "configuration error":

`Path /app/data/secret is not writable, check your DATA_DIR settings.`

As this is a docker deployment, shouldn't this be handled by the image?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by p3kj** [comment]
Issue is still present in version 3.8-2 `/app/data/secret` is still under root ownership

**Comment by nijel** [comment]
Recent versions run completely under weblate user, so please fix this manually. It could happen if you used older version and upgraded to recent not using root.
