### ISSUE TITLE
Getting "Bad gateway" error from container's nginx server

### ISSUE THREAD

**Issue by dnyamy** [WeblateOrg/docker#1286]
### Describe the issue

Hello,
I am trying to migrate my weblate (docker) instance to new server.
After my server has been under cyber attack, I was forced by hosting provider to reinstall every thing. 
Fornunately I have a backup of the whole server.

So back to weblate. 
On the new instance, I have installed docker and copied the volumes from the backup 

> weblate-docker_postgres-data
> weblate-docker_redis-data
> weblate-docker_weblate-data

I am able to build and start the containers 

> 63aa4f839a8c   weblate/weblate:4.1-1                                  "/app/bin/start runs…"   18 minutes ago   Up 18 minutes   4443/tcp, 0.0.0.0:8383->8080/tcp, :::8383->8080/tcp   weblate-docker_weblate_1
> 3a8e52a304e0   redis:4-alpine                                         "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes   6379/tcp                                              weblate-docker_cache_1
> 354b58894022   postgres:11-alpine                                     "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes   5432/tcp                                              weblate-docker_database_1

But when I try to access weblate from the brower I get a "502 Bad Gateway" error from the container's nginx server.
Looking to the logs, I can see these details : 

> weblate_1   | nginx stderr | 2021/11/30 17:01:43 [crit] 178#178: *1 connect() to unix:///run/uwsgi/app/weblate/socket failed (13: Permission denied) while connecting to upstream, client: 192.168.48.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/weblate/socket:", host: "weblate.cphlabs.net"

Please would you mind helping me to get what exactly is wrong ?
Thanks and regards

Dn

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

**Comment by nijel** [comment]
There should be some errors earlier in the log - probably uwsgi failed to startup.

Maybe the permissions on the files in restored volumes are wrong?
