### ISSUE TITLE
log the real remote IP in the docker logs, nginx stdout

### ISSUE THREAD

**Issue by szjozsef** [WeblateOrg/docker#1306]
### Describe the problem

in the docker logs, nginx stdout I can see the docker host's bridge IP instead of the real remote hosts IP

### Describe the solution you'd like

It would be nice to see the real IP logged there

### Describe alternatives you've considered

I tried to configure the nginx remote_ip module by mounting a config file to the /etc/nginx/conf.d/ folder as nginx_log.conf 
something like:

```
real_ip_header          X-Forwarded-For;
set_real_ip_from        172.16.0.0/12;

```

Now I can see the real remote address in the docker logs !

### Screenshots
Original logs:
```
nginx stdout | 172.17.0.1 - - [15/Dec/2021:14:32:06 +0200] "GET / HTTP/1.1" 200 10073 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
```

### Additional context

On the docker host I have a reverse proxy configured to server the http/https connections to weblate.

**Comment by nijel** [comment]
It could be generated based on [WEBLATE_IP_PROXY_HEADER](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_IP_PROXY_HEADER)...

**Comment by szjozsef** [comment]
That of course is configured, but it's not working, at least for me

**Comment by nijel** [comment]
Yes that's what I meant - we already have configuration for that and the nginx configuration could be adjusted based on that. Somebody has to implement that, though ;-)
