### ISSUE TITLE
Weblate 4.10 upgraded Django to 4.0

### ISSUE THREAD

**Issue by kidwm** [WeblateOrg/docker#1318]
### Describe the issue

Django 4.0 has changed the format of `CSRF_TRUSTED_ORIGINS`

https://docs.djangoproject.com/en/dev/releases/4.0/#format-change

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. upgrade weblate to 4.10 with docker
2. login: "CSRF verification failed. Request aborted."

### Expected behavior

login successful.

### Exception traceback

```pytb
weblate_1   | gunicorn stderr | Forbidden (Origin checking failed - http://example.com does not match any trusted origins.): /accounts/login/
```

### Additional context

The upgrading commit:

https://github.com/WeblateOrg/docker/commit/aec0ac4e8176aa33525fdcecfd43331becdf3294

Is it okay to let a bot do major version upgrading?

**Comment by nijel** [comment]
Effectively, the upgrade was allowed by releasing Weblate 4.10, doing the last part by the bot is definitely okay.

What is not that okay is that the documentation did not reflect changes caused by this, see also https://github.com/WeblateOrg/docker/issues/1314.

**Comment by kidwm** [comment]
@nijel how to set `CSRF_TRUSTED_ORIGINS` beside `WEBLATE_SITE_DOMAIN` in `docker-compose.override.yml`?

**Comment by nijel** [comment]
This setting is currently not managed by Weblate, you can use https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization
