### ISSUE TITLE
No access to vcs (git) of projects in weblate

### ISSUE THREAD

**Issue by wiedsche** [WeblateOrg/docker#139]
Since I am using weblate (running through docker-compose) with standard password authentication, I am not able to access the internal weblate vcs (git) to resolve merge issues.

Error:
git clone https://myweblate/git/foo/webapp-dev/
Cloning into 'webapp-dev'...
Username for 'https://mywablate': usera
Password for 'https://usera@translate.chemmedia.de':                                                                 

fatal: Authentication failed for 'https://myweblate/git/foo/webapp-dev/'  

Login through the website works flawlessly.
What could be a reason for this? Where can I find some debug information?

Without git access I am not able to resolve merge issues.

**Comment by nijel** [comment]
You're probably authenticating wrongly - the git access needs API token, not your password.

**Comment by wiedsche** [comment]
Great! This was the mistake. Now access works. Might it be that is not documented enough? I found now (after knowing i have to use the web api key) this page, that explains how to merge on conflicts: https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations

There is no word, that password has to be the apikey instead of the regular password for weblate. There is only in the example something said about, that the apikey has to be used. Perhaps it would be good to enhance the documentation in this point.

Thank you for your help.

**Comment by nijel** [comment]
It's documented in git exporter docs (https://docs.weblate.org/en/latest/admin/optionals.html#usage), but it indeed could be more visible.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
