### ISSUE TITLE
4.12.2-1 not published in docker hub

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/docker#1499]
### Describe the issue

Build failed, I guess.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

**Comment by nijel** [comment]
The publish failed for some reasons, I need to investigate that: https://github.com/WeblateOrg/docker/actions/runs/2311856444

**Comment by nijel** [comment]
Seems some issue with caches, trying to start it again, hopefully it works this time...
