### ISSUE TITLE
gunicorn stderr | Forbidden (Origin checking failed - https://weblate.example.org does not match any trusted origins.): /accounts/login/

### ISSUE THREAD

**Issue by ecx0d** [WeblateOrg/docker#1509]
### Describe the issue

any login is impossible

I already posted the bug here but it was removed.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

try to login

**Comment by nijel** [comment]
Does [WEBLATE_SITE_DOMAIN](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_SITE_DOMAIN) match the URL you are using to access Weblate?

Using reverse proxy? You need to pass some headers to Weblate container, see https://docs.weblate.org/en/latest/admin/install/docker.html#using-own-ssl-certificates

**Comment by a-zAz-Z0-9** [comment]
How do I write this for apache2?

```nginx
server {
    listen 443;
    listen [::]:443;

    server_name <SITE_URL>;
    ssl_certificate /etc/letsencrypt/live/<SITE>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<SITE>/privkey.pem;

    location / {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_pass https://127.0.0.1:<EXPOSED_DOCKER_PORT>;
    }
}
```

I tried this. I get no errors from apache but it prolly is wrong. I am not sure about the `$host` and `$proxy_add_x_forwarded_for`

```apache2
<VirtualHost *:443>
    ServerName https://weblate.example.com

    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / https://weblate.example.com/
    ProxyPreserveHost On

    Header set HOST $host
    Header set X-Forwarded-Proto https
    Header set X-Real-IP 185.205.246.181
    Header set X-Forwarded-For $proxy_add_x_forwarded_for
    Header set X-Forwarded-Host https://weblate.example.com

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/weblate.example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/weblate.example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/weblate.example.com/fullchain.pem

    ErrorLog ${APACHE_LOG_DIR}/error-weblate.log
    CustomLog ${APACHE_LOG_DIR}/access-weblate.log combined
</VirtualHost>
```

**Comment by nijel** [comment]
ProxyPreserveHost should do it, there is no need to add HOST header again...

**Comment by NLueg** [comment]
Hi there, I actually run into the same problem. 
I tried several things, but it's not working. I also connect to the page via a reverse proxy (nginx) with the same domain as configured in `WEBLATE_SITE_DOMAIN`.

Like it's said in the title, I try to log in from the domain `https://weblate.example.org` and in the logs I see that `https://weblate.example.org` ist not trusted. Also, I tried to set the field `CSRF_TRUSTED_ORIGINS` to the URL but it also don't work.
I followed the instructions 1:1: https://docs.weblate.org/en/latest/admin/install/docker.html

**Comment by nijel** [comment]
See https://docs.djangoproject.com/en/4.0/ref/csrf/#how-it-works for more info on how CSRF verification works. Most likely, some of the used headers are not passed by your reverse proxy correctly. Typically, it is the `Host` header as that one is being set by the proxy to the configured proxy server.

**Comment by NLueg** [comment]
I forward every header which I found while reading more docs and googling. I tried this for several hours without any success.
In my opinion, the error more looks like that CSRF doesn't know at which URL he's hosted even with the setting `WEBLATE_SITE_DOMAIN`.

But I finally managed it to sign in by adding the `settings-override.py` with this content:

```py
CSRF_TRUSTED_ORIGINS = ["https://weblate.example.org"]
```

**Comment by ecx0d** [comment]
I found out that if I modify 'docker-compose.override.yml' and run afterwards 
```
docker-compose -f docker-compose.override.yml up -d
```
and compare with the result of 
```
docker-compose -f docker-compose.override.yml config
```
I have different things.

it looks like the dockers are caching the first values given with the yml file.
And if this values are wrong, one can go crazzy because the docker does not update the wrong values. And modifieng them and restarting the containers does not update the values inside the containers.

**Comment by nijel** [comment]
To apply changed values, you need to rebuild the container - for example, `docker compose down` and `docker-compose up` will do that.
