### ISSUE TITLE
Error after pull github

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/docker#1560]
### Describe the issue

Server connection time-out error occurs while importing changes (over 60 minutes).  The first time such a problem appeared over a month ago.  At the time, I thought it was an occasional disconnect from the server.  After disconnecting, pull did not work, only after changing one file, import was available.  Then I resumed the import, only after some time it turned out that I lost some of the translation.  There have been no other updates since then until today.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Additional context

`nginx stderr | 2022/07/22 15:05:26 [error] 251#251: *27429 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: , request: "POST /update/eso-spolszczenie/?method=merge HTTP/1.0", upstream: "http://unix:/run/gunicorn/app/weblate/socket/update/eso-spolszczenie/?method=merge", host: "weblate.eso-spolszczenie.eu", referrer: "https://weblate.eso-spolszczenie.eu/"`

This could be the cause because the import takes longer than 3600 seconds:
`	
[
/usr/local/bin/gunicorn, 
weblate.wsgi:application, 
--preload, 
--timeout, 
3600, 
--graceful-timeout, 
3600, 
--max-requests, 
10000, 
--max-requests-jitter
]`

https://sentry.io/share/issue/bbfb6769b5e7466ebe5e4c52e0585068/

**Comment by tomkolp** [comment]
@nijel Sorry to call you, but I need a solution for a while. I can't update and we have very little time to translate the new Elder Scrolls Online expansion.

**Comment by nijel** [comment]
You can use webhooks to trigger updates, these work asynchronously, see https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

**Comment by tomkolp** [comment]
> You can use webhooks to trigger updates, these work asynchronously, see https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

I don't really understand how webhoks is supposed to help me. Will it help to bypass the server timeout during "pull"? After pressing "pull" in the repository interface, the operation takes more than 60 minutes, thus the connection with the server is broken.

**Comment by nijel** [comment]
Yes, because these are handled asynchronously.

**Comment by tomkolp** [comment]
Thank you, I will try

**Comment by tomkolp** [comment]
This is how it works great. During the initial configuration, I read the description of the webhooks, but I did not know what exactly it is.
