### ISSUE TITLE
Occasional 502 Bad Gateway errors

### ISSUE THREAD

**Issue by m3Lith** [WeblateOrg/docker#1719]
### Describe the issue

I've launched a fresh AWS EC2 Debian instance with 2 CPUs + 2GBs RAM.

Installed git, docker on it. Cloned the repo. Filled the docker-compose.override.yml file.
One of the issues I have is that sometimes, during login or password reset actions, it throws 502 errors.

Docker logs show this:
```
weblate-docker-weblate-1   | nginx stdout | CLIENT_IP_HERE - - [31/Jan/2023:15:55:06 +0000] "POST /accounts/login/ HTTP/1.1" 502 150 "https://weblate.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
weblate-docker-weblate-1   | nginx stderr | 2023/01/31 15:55:06 [error] 177#177: *100 upstream prematurely closed connection while reading response header from upstream, client: CLIENT_IP_HERE, server: , request: "POST /accounts/login/ HTTP/1.1", upstream: "http://unix:/run/gunicorn/app/weblate/socket:/accounts/login/", host: "weblate.domain.com", referrer: "https://weblate.domain.com/"
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

**Comment by m3Lith** [comment]
Update: after some hours, I start getting the same errors as #1565.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1583788/215978009-26c615f1-0ed5-4947-bc90-a674b5b7205e.png">

This happens a few times, about once an hour. And after a few of those, the whole Weblate EC2 instance becomes unreachable - only a reboot helps.

**Comment by nijel** [comment]
Maybe it does not have enough memory and the containers are crashing because of that? Do you have some monitoring in place?

**Comment by nijel** [comment]
Just to provide some insight: We run typical customer instances on 4 GB, and it works just fine. 2 GB should work as well for small installations. 

If you have many CPU cores and small memory, reducing `WEBLATE_WORKERS` might be needed, see https://docs.weblate.org/en/latest/admin/install/docker.html#number-of-processes-and-memory-consumption

**Comment by m3Lith** [comment]
It's 2 cores, but I'll try setting WEBLATE_WORKERS = 2 and see if anything changes. Otherwise I'll experiment with 4GB RAM instance. Sadly I can't see memory usage stats by default in AWS, only CPU. Bet before the server hangs, I would see quite high memory usage via `top` command.

The server is only running Weblate and the installation has one component with ~1k strings, so I'm a bit surprised 2GB wouldn't be enough..

**Comment by nijel** [comment]
WEBLATE_WORKERS defaults to 2 in your case, so this won't change anything:

https://github.com/WeblateOrg/docker/blob/d0aefbd47c488227c8f6359a3691d6481254f115/start#L249-L254

Checking which process did consume a lot of memory might help in diagnosing, but memory leaks are always tricky to discover...
