### ISSUE TITLE
CSRF issue with Docker deployment behind proxy

### ISSUE THREAD

**Issue by jonathanvaldes** [WeblateOrg/docker#1740]
### Describe the issue

I deployed Weblate (4.15.2) following the Docker install instructions described in the [dedicated page](https://docs.weblate.org/en/latest/admin/install/docker.html), including updating the **docker-compose.override.yml** file with the following content: 

> version: '3'
> services:
>   weblate:
>     ports:
>       - 80:8080
>     environment:
>       WEBLATE_EMAIL_HOST: smtp.mydomain.org
>       WEBLATE_EMAIL_HOST_USER: "smtpuser"
>       WEBLATE_EMAIL_HOST_PASSWORD: "changeme"
>       WEBLATE_SERVER_EMAIL: "i***@mydomain.org"
>       WEBLATE_DEFAULT_FROM_EMAIL: "noreply@mydomain.org"
>       WEBLATE_SITE_DOMAIN: "webapp-translation.mydomain.org"
>       WEBLATE_ADMIN_PASSWORD: "changeme"
>       WEBLATE_ADMIN_EMAIL: "i***@mydomain.org"

The application is running in Docker on a server, and is accessible internally via HTTP on the host machine without trouble (I could login using the admin credentials, setup a bunch of things and started to get amazed by the many features offered by weblate....).
Of course this weblate instance is also available using HTTPS via a public DNS entry behind a reverse proxy (client/web-browser to reverse proxy is in HTTPS, then HTTP between the reverse proxy and the hosting server).

However, when accessing via the HTTPS URL (via reverse proxy) I found out that I was getting systematically **Permission Denied. CSRF verification failed. Request aborted.**, upon using contact form or logging in.

I looked up online and found the [Issue 1912](https://github.com/WeblateOrg/weblate/issues/1912) and tried all the proposed solutions listed there but none seems to work at the moment in my case.

Now issue 1912, was supposedly flagged as enhancement and added to the version 4.14 according to this:
![image](https://user-images.githubusercontent.com/28099733/218282711-dda2f2c2-720d-4d68-86b2-5e5d26270aec.png)
Unfortunately, I might be a bit dumb ... but I'm still facing it... and even after reading this issue (and the document) quite a few time... I've yet to find what I'm doing wrong in the end.

Any obvious solution I missed ?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Follow Docker install instructions and setup HTTPS DNS entry behind reverse proxy
2. Access the application via the HTTPS URL.
3. Submit the contact form (or login)
4. See error "Permission Denied. CSRF verification failed. Request aborted."

### Expected behavior

It should not show the CSRF error.

**Comment by jonathanvaldes** [comment]
Sooo... I finally found the way to resolve the issue I had... and I'm leaving the answer here for who ever like me may be stuck on that one:

You indeed have to create a settings-override.py in the **/var/lib/docker/volumes/weblate-docker_weblate-data/_data** folder and set the value: **CSRF_TRUSTED_ORIGINS = ['https://weblate.yourdomainname.org']** in it.

Now 3 important points not to miss:
 - You MUST start the URL with **https** (or http).
 - You MUST set this variable as a list of values (using ['value1' 'value2',...] syntax)
 - You MUST make sure the file created is owned (or at least usable by) weblate user in the folder

Then it should finally work.
This being said, I believe my set up is quite classic, and I hope the weblate dev team will consider in the future having a "WEBLATE_CSRF_TRUSTED_ORIGINS" env variable we could set for this instead of dealing with python customs files via the volume... or even just set this value by default by picking up the **WEBLATE_SITE_DOMAIN** value.

**Comment by nijel** [comment]
The root cause here is most likely that `Host` header is missing or not matching. Configure your reverse proxy, see https://docs.weblate.org/en/latest/admin/install/docker.html#using-own-ssl-certificates for example configuration.
