### ISSUE TITLE
include examples

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/docker#18]
would be nice to include examples in weblate container

https://docs.weblate.org/en/latest/admin/continuous.html#example-generating-mo-files-in-repository

```
# docker-compose exec --user root weblate env TERM=$TERM  bash -l
root@e5b7cb893cc5:/tmp# find / -name git-merge-gettext-po | wc -l
0
root@e5b7cb893cc5:/tmp# 
```

**Comment by glensc** [comment]
`pip` doesn't install them, so they need to be loaded by some other means to image?

**Comment by nijel** [comment]
Maybe it would make sense to include hook scripts even with the package, it would then go into docker automatically...

**Comment by glensc** [comment]
by package you mean pypi package? yes why not. just hope they are usable out of the box!

**Comment by nijel** [comment]
They are usable (it's what you get in the docker), but examples and docs are not included there.
