### ISSUE TITLE
4.17 is not published on dockerhub

### ISSUE THREAD

**Issue by afridlund85** [WeblateOrg/docker#1807]
### Describe the issue

Hi. The image for 4.17 seems to be missing.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

**Comment by nijel** [comment]
I forgot to push the tag. 

Done now: https://github.com/WeblateOrg/docker/releases/tag/4.17-1

Publish is in progress: https://github.com/WeblateOrg/docker/actions/runs/4751820191

**Comment by afridlund85** [comment]
thank you !
