### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by aol-nnov** [WeblateOrg/docker#1842]
### Describe the issue

was trying to start `weblate/weblate:edge` and `weblate/weblate:latest` with `docker-compose.yml` from this repo

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

bring up stack with aforementioned compose file

see the [weblate.log](https://github.com/WeblateOrg/docker-compose/files/11517707/weblate.log) attached

upon `2023-05-19 17:13:07,017 DEBG stdout: ACKNOWLEDGED -> READY` log line container is stopped

### Expected behavior

containers are up and running, service is accessible via web

**Comment by aol-nnov** [comment]
Thanks for fixing this, @nijel! Any chance this fix will land in `latest` docker builds so I can test the fix?

To be honest, I'm not much into switching to `edge` in my semi-prodution environment, ha!..

Otherwise, I'm more than happy with my workaround in the stack definition file.

**Comment by nijel** [comment]
`edge` is typically safe to run, but I understand your doubts. I will probably tag it during the next week.

**Comment by aol-nnov** [comment]
Ok, thanks a lot. Looking forward to it!
