### ISSUE TITLE
Outdated docker image on dockerhub

### ISSUE THREAD

**Issue by KwadroNaut** [WeblateOrg/docker#1852]
### Describe the issue

On [dockerhub](https://hub.docker.com/r/weblate/weblate) the default docker file is using debian 10.4, oldstable. See the [docker file ](https://hub.docker.com/r/weblate/weblate/dockerfile).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. go to https://hub.docker.com/r/weblate/weblate/dockerfile
2. see FROM debian:10.4-slim

### Expected behavior

Expected something like debian:stable-slim or python:3.11.3-slim-bullseye like in `main` https://github.com/WeblateOrg/docker/blob/main/Dockerfile

**Comment by nijel** [comment]
It's just the dockerfile which they display, the images are up to date. We've switched away from building images there years ago and the file seems to be from that time.

Any suggestions how to bring it in sync?
