### ISSUE TITLE
skipping extra steps on first run

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/docker#19]
Is there reason why these are left as manual steps?

```
Setup the environment

docker-compose run --rm weblate migrate
docker-compose run --rm weblate collectstatic --noinput
# Note the admin password from this setp.
docker-compose run --rm weblate createadmin
```

these could be embeded into `weblate` entrypoint, or use some [ephemeral container](http://stackoverflow.com/a/35895156/2314626)

`createadmin` supports specifying password, so could use it as another env as default admin pass:
```
  --password PASSWORD   Password to set, random is generated if not specified
```

**Comment by nijel** [comment]
The first two steps definitely could be done automaticaly (collectstatic probably even could be done on container build).

I'm not sure what is best approach for the admin creation, in current setup it creates user with random password.

**Comment by glensc** [comment]
i did not say to do any of the steps at build time.

just two approaches:
- run in entrypoint
- run ephemeral as dependency to weblate container

those both are "runtime"

**Comment by glensc** [comment]
btw, `createadmin` can't be ran twice. it gives error that admin user already present.

so i propose:
-  run those three tasks somewhere (either one is fine), but i guess entrypoint-solution is easier to understand?
- run createadmin task if ADMIN_PASSWORD env is set

so users can run the `createadmin` themselves, and if they don't ADMIN_PASSWORD is used to set password. and if that isn't set either password is set automatically and they have to use `docker-compose logs` to find it.
