### ISSUE TITLE
Docker container start-up fails with permission denied error

### ISSUE THREAD

**Issue by RobinWeitzel** [WeblateOrg/docker#1911]
### Describe the issue

Starting a new weblate server following the instructions [here](https://docs.weblate.org/en/latest/admin/install/docker.html) fails with a 
"permission denied" error.
This occurs on multiple different systems and both with older and newer Weblate versions (though the error is different between v4.17 and v4.18).
All systems are RHEL systems.

I saw a related issue https://github.com/WeblateOrg/docker/issues/1831 but the suggestions to use the "bleeding" version did not fix it either.

Version I tested:
edge
bleeing
v4.18
v4.17

Logging into the container while it is running and checking the permissions of the /tmp/nginx folder gives me: "drwxr-x---, 2 root root 40 Jul 26 09:47 nginx"

I also tried turning "read_only" in the docker-compose file to "false".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Download docker-compose file from GitHub: https://github.com/WeblateOrg/docker-compose.git
Set "WEBLATE_SITE_DOMAIN" in environment file
Run "sudo docker-compose up" in the directory

Wait for the DB & Redis to start up.
The Web container starts up and performs migrations.
After that if fails (see screenshots).

### Expected behavior

Container is able to write to /tmp/nginx and starts up normally

### Screenshots

![error_4 18](https://github.com/WeblateOrg/docker/assets/12135433/a7068b74-5dae-41f3-aef7-39307a9765bc)
![error_4 17](https://github.com/WeblateOrg/docker/assets/12135433/7f20a6ff-17e5-453d-8360-0281db43b95c)

### Additional context

I have an old server where version 4.14 is running on. That version works but if I go to that server and try to launch version 17 or 18 it fails with the above errors as well.

**Comment by nijel** [comment]
You either need /tmp volume or disabling read_only for weblate container.
