### ISSUE TITLE
add docker-compose-production.yml for production setup

### ISSUE THREAD

**Issue by mobidev111** [WeblateOrg/docker#2]
* add script to turn on production settings, e.g. disable debug mode

* add & configure memcached for caching
https://hub.docker.com/_/memcached/

* add &configure file-based caches

* configure email adresses etc. by envirionment variable from docker-compose file

**Comment by nijel** [comment]
I think it does not make sense to have two different environments, the default one should be production ready.

Checklist:

* [ ] disable debug mode (or configurable in environment)
* [ ] email addresses configuration from environment
* [ ] site name and URL configuration (configure Site model and ALLOWED_HOSTS)
* [ ] add and configure memcached
* [ ] configure file based cache for avatars
* [ ] serve static content by nginx
* [ ] serve dynamic content by uwsgi
* [ ] enable cron job for offloading indexing
* [ ] generate SECRET_KEY on machine build

Pull requests are welcome :-).

**Comment by nijel** [comment]
Some code for inspiration: https://github.com/erroneousboat/docker-django

**Comment by nijel** [comment]
Most of that should be addressed by #12.
