### ISSUE TITLE
WEBLATE_SOCIAL_AUTH_GITLAB_SCOPE not available

### ISSUE THREAD

**Issue by lahdekorpi** [WeblateOrg/docker#228]
GitLab auth defaults to scope: `['api']` and while this works, it is an unnecessarily wide scope to have when `['read_user']` would suffice.

The env parameter is, however, not available and setting: `WEBLATE_SOCIAL_AUTH_GITLAB_SCOPE` has no effect.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by lahdekorpi** [comment]
That was amazingly fast. Thank you!
I'll test right after the Travis build has completed.
