### ISSUE TITLE
podman-compose can't run the nginx: weblate-site.conf: Permission denied

### ISSUE THREAD

**Issue by icesvz** [WeblateOrg/docker#2340]
### Describe the issue

When I run the webplate on podman I got an error: 
/app/bin/start: 263: cannot create /tmp/nginx/weblate-site.conf: Permission denied

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1 Fresh install on Centos 8 podman-compose version: 1.0.6 podman version 4.5.1 

2 podman-compose up 

3  I use these images:

docker.io/weblate/weblate   latest      8821653277e8  5 days ago    1.05 GB
docker.io/library/postgres  16-alpine   9a510ccf1de4  2 months ago  246 MB
docker.io/library/redis     7-alpine    435993df2c8d  4 months ago  42.2 MB

4 weblate-docker_weblate_1 cant start  the error is /app/bin/start: 263: cannot create /tmp/nginx/weblate-site.conf: Permission denied
 

### Expected behavior

I expect a running weblate-docker_weblate_1  container 

### Screenshots

![weblate-for-github-Screenshot_2024-05-08_18-33-18](https://github.com/WeblateOrg/docker/assets/46041560/8aeea6d8-03cd-4a44-a35e-cc8c00d17778)

### Additional context

> podman exec  --user=0  -it weblate-docker_weblate_1 chmod a=rwx /tmp/nginx/ 

chmod  inside the container fix the problem  but this is not a normal

**Comment by nijel** [comment]
You are missing tmpfs mounts, see https://github.com/WeblateOrg/docker-compose/blob/d6fda2126e324644482c846f64d248a77822012e/docker-compose.yml#L4-L6

(Or do not run container read-only).
