### ISSUE TITLE
memcached 

### ISSUE THREAD

**Issue by brusand** [WeblateOrg/docker#237]
hi
i try to docker-compose up the last version on ubuntu 1.18 and i have this issue
weblate_1   | memcached is unavailable - sleeping
weblate_1   | nc: getaddrinfo for host "cache" port 11211: Name or service not known

any help ?
best regards 
Bruno

**Comment by nijel** [comment]
Are you using own docker-compose? It should no longer use memcached, but redis instead.

**Comment by brusand** [comment]
yes i use docker-compose up

Le ven. 24 mai 2019 à 21:01, Michal Čihař <notifications@github.com> a
écrit :

**Comment by brusand** [comment]
yes i didn't change any line in your docker-compose.yml file

Le ven. 24 mai 2019 à 21:01, Michal Čihař <notifications@github.com> a
écrit :

**Comment by nijel** [comment]
But the memcached configuration has to come from somewhere - it's not part of the default setup. Something has to set `MEMCACHED_HOST` variable.

https://github.com/WeblateOrg/docker/blob/16b1e09a2f23d70f9ef20868a46c39c8f559dff6/start#L36-L57
