### ISSUE TITLE
WEBLATE_WORKERS=1 spawns many more processes

### ISSUE THREAD

**Issue by Derkades** [WeblateOrg/docker#2407]
### Describe the issue

Setting WEBLATE_WORKERS to 1 means concurrency is set to 0 in some places, due to a floored divide by two. We would like to run with 1 celery worker to reduce memory usage. The default results in ~1.7GiB, WEBLATE_WORKERS=1 results in ~8GiB of memory used. We were hoping for something closer to 0.5-1GiB.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Set WEBLATE_WORKERS=1

**Comment by nijel** [comment]
Memory usage should get better in the next release, see https://github.com/WeblateOrg/weblate/issues/11686.

**Comment by Derkades** [comment]
Thank you! That helps for small instances.
