### ISSUE TITLE
Inconsistencies in variables

### ISSUE THREAD

**Issue by gabn88** [WeblateOrg/docker#25]
If you want to set environment variables that are a boolean, you should set them like:

OFFLOAD=1 or 0 (not True/False)

and if you want to set a string you set SERVER_EMAIL=abc@abc.com  (without quotes)

for allowed_hosts nothing seems to work :(

Took me an hour to find out *-)

**Comment by gabn88** [comment]
And also one issue I'm having (when using docker-machine) is that in you guide you set the cronjobs on the local machine, instead of on the remote machine. That way the local machine always has to initiate the cronjobs, to make sure the jobs run on the remote machine.

Better imo would be a seperation of concerns. :)

**Comment by gabn88** [comment]
Okay, I have fixed it like this:

on the remote machine insert the following crontab, where a558b065544a is the container id (via docker ps).

* * * * * /usr/bin/docker exec a558b065544a weblate update_index >> /root/crontab.log 2>&1
0 0 * * * /usr/bin/docker exec a558b065544a weblate cleanuptrans >> /root/crontab.log 2>&1
0 * * * * /usr/bin/docker exec a558b065544a weblate commit_pending --all --age=24 >> /root/crontab.log 2>&1

**Comment by nijel** [comment]
I've updated docs to clarify values and include examples, hopefully it's easier to understand now.

**Comment by gabn88** [comment]
Super, thanks!
