### ISSUE TITLE
Bleeding Docker Image is not being created

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/docker#2556]
### Describe the issue

No Bleeding Docker for 3 days.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

No Bleeding Docker for 3 days.

**Comment by nijel** [comment]
For two actually, but https://github.com/WeblateOrg/docker-compose/commit/cf74a4e2b0c8391570d3f0fa6baa10c6b34a76f2 should hopefully fix this.

**Comment by nijel** [comment]
It should build now.
