### ISSUE TITLE
Container fails to start because of existing symlink

### ISSUE THREAD

**Issue by raymondelooff** [WeblateOrg/docker#2579]
### Describe the issue

Because of changes in [c5a1c3b](https://github.com/WeblateOrg/docker/commit/c5a1c3b85de1832b2ec05d0d59d49efffc8a4b48), containers now fail to start a second time after being stopped. The start script tries to create Supervisor config file symlinks, but those `ln -s` commands fail when a symlink already exists (because they get created during the first start). Adding the `-f` flag to all the symlink commands will likely fix the issue.

```
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-backup.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-beat.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-celery.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-memory.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-notify.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/celery-translate.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/check.conf': File exists
weblate-1  | ln: failed to create symbolic link '/var/run/supervisor.conf.d/web.conf': File exists
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Start a new container
2. Stop the container, don't remove it
3. Start the container again

**Comment by nijel** [comment]
We should also add tests to cover this situation while fixing this.

**Comment by nijel** [comment]
This doesn't happen in the recommended setup when using `tmpfs` for `/run`, as in that case, the `tmpfs` doesn't survive the container restart.
