### ISSUE TITLE
Not running on armhf

### ISSUE THREAD

**Issue by thopiekar** [WeblateOrg/docker#26]
I've got a QNAP NAS here and liked to install your software here.
When trying to run the container at the end, the UI tells about a "wrong exec format" error. So I guess the image contains binaries for i386 or amd64 CPUs.

Any chance to get a armhf build?

Thanks!

**Comment by nijel** [comment]
There is really nothing architecture specific in Weblate Dockerfile. We're basing on nginx and debian:jessie-backports images and IMHO these should work just fine on arm, but I really have no knowledge how this works on Docker.

**Comment by jokester** [comment]
Sorry for digging old issues but I guess arm images are quite doable at the moment: there are github actions to run `docker buildx` and push to docker hub.

When using this, we will need to switch from docker hub's auto build, hope that won't be a problem.

**Comment by jokester** [comment]
Trying to do something in #655

**Comment by nijel** [comment]
Sounds great, I wanted to switch to building on GitHub as well to publish only images where tests pass, see https://github.com/WeblateOrg/docker/issues/601

**Comment by nijel** [comment]
Hundreds of builds later, the CI finally works and first arm images are available on https://hub.docker.com/r/weblate/weblate/tags
