### ISSUE TITLE
Subtitle files not available after upgrading to 3.7

### ISSUE THREAD

**Issue by lahdekorpi** [WeblateOrg/docker#267]
Ran `docker-compose stop && docker-compose pull && docker-compose up` to upgrade to 3.7. Everything seemed to go as it should and I didn't get any errors.

Subtitle files (SubRip subtitle file) is, however, not available:
![image](https://user-images.githubusercontent.com/570545/59967493-34031a00-9533-11e9-9760-8c6ecf2b697b.png)

The upgrade documentation states:
> There are new file formats, you might want to include them in case you modified the WEBLATE_FORMATS.
I don't however have a modified `WEBLATE_FORMATS`.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by lahdekorpi** [comment]
Thank you! This worked.

For anyone else running into the same issue; a workaround while waiting for the newer image you can install the Python package manually inside the container and restart it:
```bash
pip3 install aeidon==1.2.1
```

**Comment by nijel** [comment]
The new image is already there under the `edge` tag.
