### ISSUE TITLE
Configuration updates?

### ISSUE THREAD

**Issue by vjrj** [WeblateOrg/docker#27]
I updated some environmental variables (Google OAUTH, etc) but seems that restarting with docker-compose (stop/start) it's not enough to taking into account these new environmental variables. 

Any tip? Because I have configured a project & components and I'm worry to lost that part.

TIA,

**Comment by nijel** [comment]
IMHO restart of the container should be enough, but I'm no way Docker expert.

**Comment by vjrj** [comment]
Yes, you are right. I was using only `docker-compose stop|start` and start, but it worked using `docker-composer down|up`. Thanks
