### ISSUE TITLE
Latest docker images missing

### ISSUE THREAD

**Issue by carstencodes** [WeblateOrg/docker#2741]
### Describe the issue

Hi, currentlly, neither docker hub nor ghcr.io provide a (labeled) image for Weblate 5.8.1.

The ghcr publish action timed out, hence, the release was never created.

Can you please take a look, what happens here and provide the latest images?

Regards

Carsten

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

cf. Build Log at

https://github.com/WeblateOrg/docker/actions/runs/11343544181/job/31546318936

### Expected behavior

Labeled issues on ghcr.io and docker hub

### Additional context

https://github.com/WeblateOrg/docker/actions/runs/11343544181/job/31546318936

**Comment by nijel** [comment]
Sorry, I forgot to tag the release in the docker repo, fixed now.

**Comment by carstencodes** [comment]
Geez, that was fast. Thank you very much.
