### ISSUE TITLE
Add Docker variable for WEBLATE_GPG_IDENTITY

### ISSUE THREAD

**Issue by apgrucza** [WeblateOrg/docker#278]
I would like to be able to set `WEBLATE_GPG_IDENTITY` from a Docker environment variable.

It would be ideal if any Weblate setting could be set from a Docker environment variable (as suggested in #57) but for now, all I need is `WEBLATE_GPG_IDENTITY`.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by apgrucza** [comment]
Thanks for the fix. Doesn't look like GPG is installed in the Docker image though. Should the Dockerfile also be modified to install GnuPG?

**Comment by nijel** [comment]
Good point, I've just added it.
