### ISSUE TITLE
ssl sertificate expired

### ISSUE THREAD

**Issue by bernex** [WeblateOrg/docker#29]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

gzip: stdin: unexpected end of file
tar: Child returned status 1

ERROR: Service 'weblate' failed to build: The command '/bin/sh -c curl https://dl.cihar.com/weblate/Weblate-2.9.tar.gz | tar xzf - --strip-components=1 --no-same-owner -C /app Weblate-2.9/examples' returned a non-zero code: 2

**Comment by nijel** [comment]
When I access the site, the certificate is valid till 27.3.2017 (and issued 26.12.2016), can you reproduce this?
