### ISSUE TITLE
openshift 3 failed chmod app/data

### ISSUE THREAD

**Issue by brusand** [WeblateOrg/docker#292]
hi,
i try to deploy the latest weblate docker image to openshift3 and it fail to the chown app/data :
  | chown: changing ownership of '/app/data':   Operation not permitted

is there a fix or a turn around ?
i try to deploy weblate with  yml descriptors
(i have an other issue , i have to migrate postgresl to a cenos distrib (with change of env POSGRES_xxx to POSTGRESQL_xxx)

thx
Best regards
Bruno

**Comment by nijel** [comment]
The Docker container currently needs to be executed as root, so maybe that's the problem?

Anyway Weblate from https://github.com/WeblateOrg/weblate/ should work fine with openshift 3, the integration was done by @alesrosina  and @GrahamDumpleton, I have no experience with that platform.

**Comment by GrahamDumpleton** [comment]
Deployment on OpenShift 3 relies on you building your own image in the OpenShift cluster using an S2I build. See the template files for deployment in:

* https://github.com/WeblateOrg/weblate/tree/master/openshift3

**Comment by brusand** [comment]
not easy ...

Building wheel for pycairo (setup.py): finished with status 'error'
--
  | ERROR: Complete output from command /opt/app-root/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nej2y9y4/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5wa_ofkk --python-tag cp35:
  | ERROR: running bdist_wheel
  | running build
  | running build_py
  | creating build
  | creating build/lib.linux-x86_64-3.5
  | creating build/lib.linux-x86_64-3.5/cairo
  | copying cairo/__init__.py -> build/lib.linux-x86_64-3.5/cairo
  | copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.5/cairo
  | copying cairo/py.typed -> build/lib.linux-x86_64-3.5/cairo
  | running build_ext
  | Package cairo was not found in the pkg-config search path.
  | Perhaps you should add the directory containing `cairo.pc'
  | to the PKG_CONFIG_PATH environment variable
  | No package 'cairo' found
  | Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1
  | ----------------------------------------
  | ERROR: Failed building wheel for pycairo
  | Running setup.py clean for pycairo
  | Failed to build pycairo
  | Installing collected packages: setuptools, wheel, pycairo
  | Running setup.py install for pycairo: started
  | Running setup.py install for pycairo: finished with status 'error'
  | ERROR: Complete output from command /opt/app-root/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nej2y9y4/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-088ig3np/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-zgxi7jm2/overlay --compile --install-headers /opt/app-root/include/site/python3.5/pycairo:
  | ERROR: running install
  | running build
  | running build_py
  | creating build
  | creating build/lib.linux-x86_64-3.5
  | creating build/lib.linux-x86_64-3.5/cairo
  | copying cairo/__init__.py -> build/lib.linux-x86_64-3.5/cairo
  | copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.5/cairo
  | copying cairo/py.typed -> build/lib.linux-x86_64-3.5/cairo
  | running build_ext
  | Package cairo was not found in the pkg-config search path.
  | Perhaps you should add the directory containing `cairo.pc'
  | to the PKG_CONFIG_PATH environment variable
  | No package 'cairo' found
  | Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1
  | ----------------------------------------
  | ERROR: Command "/opt/app-root/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nej2y9y4/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-088ig3np/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-zgxi7jm2/overlay --compile --install-headers /opt/app-root/include/site/python3.5/pycairo" failed with error code 1 in /tmp/pip-install-nej2y9y4/pycairo/
  | ----------------------------------------
  | ERROR: Command "/opt/app-root/bin/python3 /opt/app-root/lib/python3.5/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zgxi7jm2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple  -- setuptools wheel pycairo" failed with error code 1 in None
  | error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/python-35-rhel7@sha256:975e9848f28b02c75b5b82ea0a0d271a166255a8a5c59b0147e18a61dfc858ce

**Comment by alesrosina** [comment]
@brusand yeah, i have also found out about this bug. I'm trying to solve it, but the basic problem is, that `openshift/python` docker image does not have`cairo` library installed by default, where `python` image for docker does.

@GrahamDumpleton maybe you have any idea how to install additional package to `openshift/python` image?

And this appeared in one of the latest releases, when Cairo library was introduced to Weblate.

**Comment by nijel** [comment]
What does actually block using official Weblate Docker images in OpenShift? Maybe it could be adjusted to be useful there as well?

As for the build, I guess that it's still Centos/RHEL underneath, so it should be matter of installing additional packages:

```
dnf install cairo-devel typelib-1_0-Pango-1_0 gobject-introspection-devel
```

**Comment by brusand** [comment]
Where is the dockerfile for the openshift build ?

**Comment by sylvainar** [comment]
Hey guys, i'm currently working on it: https://github.com/WeblateOrg/docker/pull/293

It's not working for now but i'm getting closer.

**Comment by alesrosina** [comment]
@sylvainar this sounds promising, actually that would be the best way.

**Comment by nijel** [comment]
Should be addressed by https://github.com/WeblateOrg/docker/pull/307 (based on #293).

**Comment by alesrosina** [comment]
@sylvainar i am not opening new issue, just a question related to this one - I've tried your solution and it works, except when I trigger new deployment (let it be manual or config change) - the old deployment does not finish its self, so new deployment fails to deploy. I need to manually delete previous deployment and trigger new deployment and then it works. Any idea what is going on?
