### ISSUE TITLE
Make this image run on openshift

### ISSUE THREAD

**Issue by sylvainar** [WeblateOrg/docker#298]
I'm opening an issue to track my progress on this subject.

- [x] Change the default port (can't be less than 1024) #291 
- [x] Image can be run by any user #293 
- [x] Support for `REDIS_PASSWORD` env var isn't complete, the startup script acts weird

**Comment by nijel** [comment]
The `REDIS_PASSWORD` issue should be addressed in f72ea4e.

**Comment by sylvainar** [comment]
Great, has it been merged?
