### ISSUE TITLE
Weird behavior with redis password

### ISSUE THREAD

**Issue by sylvainar** [WeblateOrg/docker#301]
When I want to run this image with a redis password, I got this on startup:

```
Running migrations:
  No migrations to apply.
Removing corrupted schedule file: ValueError("invalid literal for int() with base 10: 'myredispasswordredis:6379'")
ERROR Handled exception: ValueError: invalid literal for int() with base 10: 'myredispasswordredis:6379'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by sylvainar** [comment]
wow that was quick, thanks
