### ISSUE TITLE
WEBLATE_PORT conflict with variables set by Kubernetes

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/docker#302]
nginx fails to start with this error:

2019-07-15 20:19:32,467 INFO spawned: 'nginx' with pid 548
2019/07/15 20:19:32 [emerg] 548#548: invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
nginx: [emerg] invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
2019-07-15 20:19:32,503 INFO exited: nginx (exit status 1; not expected)
2019-07-15 20:19:33,508 INFO spawned: 'nginx' with pid 550
2019/07/15 20:19:33 [emerg] 550#550: invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
nginx: [emerg] invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
2019-07-15 20:19:33,546 INFO exited: nginx (exit status 1; not expected)
2019-07-15 20:19:35,554 INFO spawned: 'nginx' with pid 552
2019/07/15 20:19:35 [emerg] 552#552: invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
nginx: [emerg] invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
2019-07-15 20:19:35,592 INFO exited: nginx (exit status 1; not expected)
2019-07-15 20:19:38,598 INFO spawned: 'nginx' with pid 556
2019/07/15 20:19:38 [emerg] 556#556: invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
nginx: [emerg] invalid host in "tcp://10.35.242.86:80" of the "listen" directive in /etc/nginx/sites-enabled/default:2
2019-07-15 20:19:38,637 INFO exited: nginx (exit status 1; not expected)

**Comment by nijel** [comment]
What's your setting for `WEBLATE_PORT`?

**Comment by paulpach** [comment]
I did not set it at all.   The docker image by default is picking up  tcp://10.35.242.86:80
I think the docker image should default to just 80

**Comment by nijel** [comment]
It defaults to 80:

https://github.com/WeblateOrg/docker/blob/e70e22e27a6ae0940052161c14a91fc333111af8/start#L6-L8

And it's used directly in the configuration:

https://github.com/WeblateOrg/docker/blob/e70e22e27a6ae0940052161c14a91fc333111af8/etc/nginx/default.tpl#L2

**Comment by paulpach** [comment]
It looks like the WEBLATE_PORT is being set in ```/etc/profile.d/weblate.sh```

Here are the contents of that file:
```
export POSTGRES_DATABASE='weblate'
export POSTGRES_HOST='database'
export POSTGRES_PASSWORD=''
export POSTGRES_PORT='5432'
export POSTGRES_SSL_MODE='prefer'
export POSTGRES_USER='weblate'
export REDIS_HOST='cache'
export REDIS_PORT='6379'
export WEBLATE_ADMIN_EMAIL='paul@blockstory.net'
export WEBLATE_ADMIN_NAME='Paul Pacheco'
export WEBLATE_ADMIN_PASSWORD='frapuchino24'
export WEBLATE_ALLOWED_HOSTS='translate.blockstory.net,*'
export WEBLATE_CMD='/usr/local/bin/weblate'
export WEBLATE_DEBUG='0'
export WEBLATE_DEFAULT_FROM_EMAIL='weblate@blockstory.net'
export WEBLATE_EMAIL_HOST='smtp.sendgrid.net'
export WEBLATE_EMAIL_PASSWORD='6Q7SrQh8M6hc'
export WEBLATE_EMAIL_PORT='587'
export WEBLATE_EMAIL_USER='paulpach'
export WEBLATE_LOGLEVEL='DEBUG'
export WEBLATE_PORT='tcp://10.35.242.86:80'
export WEBLATE_PORT_80_TCP='tcp://10.35.242.86:80'
export WEBLATE_PORT_80_TCP_ADDR='10.35.242.86'
export WEBLATE_PORT_80_TCP_PORT='80'
export WEBLATE_PORT_80_TCP_PROTO='tcp'
export WEBLATE_REGISTRATION_OPEN='1'
export WEBLATE_SERVER_EMAIL='weblate@blockstory.net'
export WEBLATE_SERVICE_HOST='10.35.242.86'
export WEBLATE_SERVICE_PORT='80'
export WEBLATE_SERVICE_PORT_HTTP='80'
export WEBLATE_SITE_TITLE='Weblate'
export WEBLATE_TIME_ZONE='America/Chicago'
```

how is weblate.sh generated?

**Comment by paulpach** [comment]
It looks like WEBLATE_PORT is set in ```/etc/profile.d/weblate.sh```

Here are the contents of that file:
```
export POSTGRES_DATABASE='weblate'
export POSTGRES_HOST='database'
export POSTGRES_PASSWORD=''
export POSTGRES_PORT='5432'
export POSTGRES_SSL_MODE='prefer'
export POSTGRES_USER='weblate'
export REDIS_HOST='cache'
export REDIS_PORT='6379'
export WEBLATE_ADMIN_EMAIL='paul@blockstory.net'
export WEBLATE_ADMIN_NAME='Paul Pacheco'
export WEBLATE_ADMIN_PASSWORD='xxx'
export WEBLATE_ALLOWED_HOSTS='translate.blockstory.net,*'
export WEBLATE_CMD='/usr/local/bin/weblate'
export WEBLATE_DEBUG='0'
export WEBLATE_DEFAULT_FROM_EMAIL='weblate@blockstory.net'
export WEBLATE_EMAIL_HOST='smtp.sendgrid.net'
export WEBLATE_EMAIL_PASSWORD='xxx'
export WEBLATE_EMAIL_PORT='587'
export WEBLATE_EMAIL_USER='paulpach'
export WEBLATE_LOGLEVEL='DEBUG'
export WEBLATE_PORT='tcp://10.35.242.86:80'
export WEBLATE_PORT_80_TCP='tcp://10.35.242.86:80'
export WEBLATE_PORT_80_TCP_ADDR='10.35.242.86'
export WEBLATE_PORT_80_TCP_PORT='80'
export WEBLATE_PORT_80_TCP_PROTO='tcp'
export WEBLATE_REGISTRATION_OPEN='1'
export WEBLATE_SERVER_EMAIL='weblate@blockstory.net'
export WEBLATE_SERVICE_HOST='10.35.242.86'
export WEBLATE_SERVICE_PORT='80'
export WEBLATE_SERVICE_PORT_HTTP='80'
export WEBLATE_SITE_TITLE='Weblate'
export WEBLATE_TIME_ZONE='America/Chicago'
```

how is weblate.sh generated?

**Comment by nijel** [comment]
That's generated from the Docker environment, that's sequel, not the cause:

https://github.com/WeblateOrg/docker/blob/e70e22e27a6ae0940052161c14a91fc333111af8/start#L94

But thanks for pointing this out, this code should not be needed anymore, so I've just removed it.

**Comment by paulpach** [comment]
I think I figured it out. 

I deploy weblate in kubernetes.  I have a service called weblate,  and kubernetes generates environment variables for each service.  Kubernetes is generating WEBLATE_PORT with this value and this is causing the problem.

So this is not an issue in your docker image,  I just need to rename the service to anything but weblate.

Thank you for looking into it.

**Comment by nijel** [comment]
Thanks for providing details. I still thing that giving Weblate container name weblate is quite usual, so we still might deal with that better...

**Comment by nijel** [comment]
I've removed the setting as apparently it breaks too many setups.

**Comment by sylvainar** [comment]
Hey there, I'm digging back this issue, why not just renaming the env var to WEBLATE_WEBSERVER_PORT or something equivalent?

I'll do another PR if you agree with this.

**Comment by nijel** [comment]
What is reason to have this configurable? The original intention was to move it from privileged port...

**Comment by sylvainar** [comment]
Yeah right
