### ISSUE TITLE
Github pull requests support

### ISSUE THREAD

**Issue by stefk** [WeblateOrg/docker#31]
Hello,

I'm trying to add support for github pull requests to this image but unfortunately I'm stuck in the last and most important part of the process, ie the actual use of that feature. I know this has been discussed several times in the issue tracker of https://github.com/WeblateOrg/weblate but none of the answers helped me to solve my problem. Here's the situation:

- I have a working install of weblate based on this image
- I've tweaked *weblate/Dockerfile* so that hub is installed and available inside the weblate container
- Once I enter that container, I can perform hub commands like `hub clone user/repo`; a */home/weblate/.config/hub* config file holds the associated credentials
- I've set `GITHUB_USERNAME` in *weblate/settings.py* to the same user written in *.config/hub*
- When I create a component, I can select "Github" in the vcs field as expected

From this point, however, all the push operations result in a `failed to push on repo: Permission denied (publickey). fatal: Could not read from remote repository.` error. I've tried various combinations of protocols/urls in the "Push url" field without success.

Could you please provide some guidance? What I'm really missing in the documentation is a simple working example of that feature. I don't even know if it's bound to the "push" button or if I should see a "pull request" available somewhere in the UI. Any help would really be appreciated!

**Comment by nijel** [comment]
At first look, you probably configure hub with wrong path, see https://docs.weblate.org/en/latest/vcs.html#setting-up-hub, where you need the hub configuration is /app/data/home/.config/hub.

**Comment by stefk** [comment]
Thanks! I just missed the `/app/data/home` vs `/home/weblate` distinction.
