### ISSUE TITLE
How to Github Auth from docker-compose?

### ISSUE THREAD

**Issue by MTRNord** [WeblateOrg/docker#36]
Using just adding the auth keys it gives me redirect_uri_mismatch. I run weblate behind a jwilder/nginx-proxy

**Comment by nijel** [comment]
Did you correctly set Authorization callback URL in the OAuth application settings on GitHub?

Also you might have [wrongly configured site name](https://docs.weblate.org/en/latest/admin/install.html#production-site) in Weblate.

**Comment by MTRNord** [comment]
I got it I have to use http even if I open weblate with https.

**Comment by nijel** [comment]
Maybe just setting [ENABLE_HTTPS](https://docs.weblate.org/en/latest/admin/config.html#std:setting-ENABLE_HTTPS) will help that as well.
