### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by lukasbisdorf** [WeblateOrg/docker#360]
When running the Weblate docker stack, and trying to upload an existing Translation memory larger than 1MB you will run into the nginx 413 error.

This one can be fixed with increasing the `client_max_body_size` config property inside the server config. 
It could either be a docker env variable, defaults to something bigger than 1MB:

```
server {
    client_max_body_size 100M;
    ...
}
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
