### ISSUE TITLE
*** Please tell me who you are.

### ISSUE THREAD

**Issue by sguilly** [WeblateOrg/docker#364]
I have this issue when i try to create a component.

I enter in docker container and apply the recommented commands but the issue is still present.

http://localhost:5080/create/component/?project=1#scratch

RepositoryException at /create/component/
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'weblate@1a0d8ed6ee4f.(none)') (128)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by sguilly** [comment]
Issue fixed with weblate/weblate:3.8-3
BIG Thanks

**Comment by Jibec** [comment]
Does this impact Weblate 3.8 or only the docker image? Should I embed you patch in the yunohost package or wait for a minor release?

**Comment by nijel** [comment]
It doesn't happen in all cases, but can happen with Weblate 3.8 as well, but there is no plan for a point release right now. All three patches are needed: https://github.com/WeblateOrg/docker/blob/master/patches/0001-Errors-Catch-ProgrammingError-as-well-when-saving-er.patch, https://github.com/WeblateOrg/docker/blob/master/patches/0001-VCS-Fix-missing-default-app-config.patch, https://github.com/WeblateOrg/docker/blob/master/patches/0002-VCS-Fix-initial-git-setup-when-home-does-not-exist.patch
