### ISSUE TITLE
feat(redis): Introduce option for external redis in-transit-encryption TLS

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/docker#370]
The current configuration does not support, if external redis is configured with TLS enabled.

Proposing to introduce an additional env variable as `REDIS_TLS=true/false` to control this.

What else is needed to have redis via TLS connected? Is this simply using redis endpoint with
- `redis://` to start with for NON TLS
- `rediss://` to start with for TLS enabled

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by mleneveut** [comment]
Hi, I tried with an Azure cache for Redis and it doesn't work.

I tried :
Redis with TLS 1.0 (default) and REDIS_TLS: "false" or REDIS_TLS: "true"
Redis with TLS 1.2 (default) and REDIS_TLS: "false" or REDIS_TLS: "true"

My conf : 

```
- name: REDIS_HOST
          value: xxx.redis.cache.windows.net
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_PASSWORD
          value: xxx
        - name: REDIS_TLS
          value: "true"
```

**Comment by nijel** [comment]
@mleneveut What kind of error do you get? Can you please clarify?

**Comment by mleneveut** [comment]
I have the error `redis is unavailable - sleeping` 

But we tried to set Azure Redis with non SSL port and it is still not working. So it may be another problem, more general with Azure Redis.

I tried to set debug log level, but I don't get any other logs.

```
        - name: WEBLATE_LOGLEVEL
          value: DEBUG
        - name: WEBLATE_DEBUG
          value: "1"
```

**Comment by mleneveut** [comment]
Well I ended up using memcached as it is just for the translations in our dev environment. So don't bother debugging Azure Redis :)

Thanks for your help.

**Comment by nijel** [comment]
After some time (currently 60 seconds) it will print more detailed error, that should give better clue what might be wrong.

**Comment by nijel** [comment]
Anyway my wild guess is that it have failed with `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate`, this can be disabled since 73fa824.

**Comment by rhofer** [comment]
Just tested with docker image 3.9.1-1 and connected to AWS redis instance with in-transit encryption. Works fine! @nijel many thanks for this feature and fix with https://github.com/WeblateOrg/weblate/issues/3146
