### ISSUE TITLE
libs removed in Dockerfile

### ISSUE THREAD

**Issue by serdyuk-alex** [WeblateOrg/docker#39]
Here is line from dockerfile:
```  
&& apt-get -y purge python-pip python-dev libleptonica-dev libtesseract-dev cython gcc g++ python-setuptools python-wheel python-pip \
```
https://hub.docker.com/r/weblate/weblate/~/dockerfile/

Why do we need to remove these packages? Actually pip/setuptools are quite useful, e.g. if I'm going to install some custom libs used in weblate scripts

**Comment by nijel** [comment]
The reason was to make the Docker image small and not contain tools most people won't use (eg. the -dev files are needed just to compile used python extensions and nobody will use that again). Leaving pip there might make sense though...

**Comment by serdyuk-alex** [comment]
These are quite small but needed tools, their sizes in bytes:
```
$ sudo apt-cache --no-all-versions show python-pip | grep '^Size: '        
Size: 97320
$ sudo apt-cache --no-all-versions show python-setuptools | grep '^Size: '   
Size: 230056
```
Weblate image size:
```
weblate/weblate                            latest                                     07dbc80bad4d        4 weeks ago         613 MB
```
So comparing to whole image size don't think it makes sense to cut these tools, also it's a bit strange to have python without package managers (eg pip)

**Comment by nijel** [comment]
As I've said before - keeping pip probably makes sense, this was primarily done to remove devel files and compiler, which do consume quite some space.
