### ISSUE TITLE
still localhost in sitename

### ISSUE THREAD

**Issue by tinect** [WeblateOrg/docker#391]
Hey,
having annoying bug when restarting weblate.
The sitename is still set to "localhost" on every start.

Is there any hint, that the set sitename will stay after reboot?

Thank you!

**Comment by nijel** [comment]
Set correct [WEBLATE_ALLOWED_HOSTS](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ALLOWED_HOSTS).

**Comment by tinect** [comment]
Ooops, had localhost as first one. Thank you! @nijel
