### ISSUE TITLE
Missing settings.py

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/docker#410]
Is it intended that with 3.9 the settings.py (etc/weblate/settings.py) is missing?

**Comment by nijel** [comment]
Yes, it now uses `settings_docker.py` shipped with Weblate.

**Comment by rhofer** [comment]
Ok, many thanks for pointing out. Closing issue.

**Comment by rhofer** [comment]
No, no breaks, as far I could see up to now. It's more about configuration where I need to set the environment vars correctly. There it is about my personal preference to stick to the code , in this case 'settings_docker.py' instead of documentation only.
