### ISSUE TITLE
Cannot generate GPG key after setting WEBLATE_GPG_IDENTITY

### ISSUE THREAD

**Issue by JonahAragon** [WeblateOrg/docker#456]
`gpg` does not appear to be installed in my Docker container:

```
[Errno 2] No such file or directory: 'gpg': 'gpg'
```

I've set `WEBLATE_GPG_IDENTITY` in `/app/data/settings-override.py`

**Comment by nijel** [comment]
Maybe you're using old container? It was added in d683f87a

Duplicate of #278
