### ISSUE TITLE
SSO auth in docker compose version

### ISSUE THREAD

**Issue by zsotesz81** [WeblateOrg/docker#458]
Hello

Is there any way to implement login through an existing sso server in the docker compose version of weblate?
Is it possible through the environment file? I created a settings.py file in /app/data/python/customize directory within the container with the following content:
AUTHENTICATION_BACKENDS = (
    # Add authentication backend here
    'weblate.accounts.auth.WeblateUserBackend',
)

INSTALLED_APPS = (
    ...
    'django-simple-sso',
    # Install authentication app here
)
I am not sure this is correct, and I also don't know which file should I include the sso server's url. I think I should put into one of the urls.py but i found more than 20 on different locations.
So could you please help me out how should I configure weblate?

**Comment by nijel** [comment]
The location of the configuration file is different, see https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization.

You can probably also use simpler approach by adding `django-simple-sso` to ` WEBLATE_ADD_APPS`, see https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ADD_APPS

**Comment by zsotesz81** [comment]
i've created the /app/data/settings-override.py and copied this code into it
AUTHENTICATION_BACKENDS = (
# Add authentication backend here
'weblate.accounts.auth.WeblateUserBackend',
)

INSTALLED_APPS = (
...
'django-simple-sso',
# Install authentication app here
) 
But unfortunately my container can't spin up due to syntax error. Is there a different syntax for settings-override.py?
I also tried WEBLATE_ADD_APPS variable, but in this case i got a "ModuleNotFoundError: No module named 'django-simple-sso'" error

**Comment by nijel** [comment]
You need to list all existing apps, the `...` part is not valid. And yes, you need to install the extra module as well - placing it into `/app/data/python` should word.

**Comment by zsotesz81** [comment]
Can you tell me what is the callback url in case of azure authentication?
I tried https://dev.translation.emea.gcds.coke.com/accounts/complete/azuread-tenant-oauth2 and some other but neither of it works.

**Comment by nijel** [comment]
Looks like trailing slash is missing in the URL.

**Comment by zsotesz81** [comment]
doesn't work with the trailing slash either, but here is what i have found:
this is the whole request url:
https://login.microsoftonline.com/b41b72d0-4e9f-4c26-8a69-f949f367c91d/oauth2/authorize?client_id=e85f5d27-ba9c-4f73-aeb6-8d30eccab3cf&redirect_uri=http://<myapp>/accounts/complete/azuread-tenant-oauth2/&state=1V93rPJmESRdoZa97oJWzExTsG72BSaM&response_type=code&scope=openid+profile+user_impersonation

the redirect_uri starts with http instead of https (http is not allowed in azure), so after i changed it to https in the url , it worked, however now i get "The server does not allow authentication. " on weblate

**Comment by zsotesz81** [comment]
Is there a way to fix the above issue somehow in weblate? I mean that the redirect_url to begin with https instead of http

**Comment by nijel** [comment]
Yes, configure [Weblate to use https](https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ENABLE_HTTPS),

**Comment by zsotesz81** [comment]
It's working now, thank you for your help

**Comment by kokoye2007** [comment]
> It's working now, thank you for your help
Do you have any guide or reference ?
I want to add SSO (google / facebook /twitter).
