### ISSUE TITLE
Machine Translation not working

### ISSUE THREAD

**Issue by pyrexx-siller** [WeblateOrg/docker#470]
Hi,

I am having errors when trying to use machine translation.

**Describe the bug**
Machine translation tab shows "The request for machine translation has failed: error" and when I click on the Translation memory tab and search something I get "This site doesn't work HTTP ERROR 405"

**Expected behavior**
Machine Translation should show similar translated strings.

**Software Version**
We are using Weblate 3.9.1 Docker on a Debian 9.

If I can provide any logs or something to help just tell me.

Thank you
S. Siller

**Comment by nijel** [comment]
Did you use older version before? Try clearing browser cache and cookies if that helps...

**Comment by pyrexx-siller** [comment]
I did and we tried multiple PCs and Browsers, sadly it did not help.

**Comment by nijel** [comment]
Most likely this had same root cause as https://github.com/WeblateOrg/docker/issues/495, it's fixed in latest docker container.
