### ISSUE TITLE
Add environment variable for Keycloak social Auth

### ISSUE THREAD

**Issue by mleneveut** [WeblateOrg/docker#474]
Hi,

I would need to use Keycloak authentication with my Weblate Docker image 3.8-5 (couldn't upgrade to newer version due to problem with Azure AKS / Redis / Postgres communication)

I understand we should add the following variables in settings.py, and would love to help with a MR, but I couldn't find the settings.py in this 'weblate docker' repo and didn't understand how to use/write a patch file.

```
if "WEBLATE_SOCIAL_AUTH_KEYCLOAK_KEY" in os.environ:
    AUTHENTICATION_BACKENDS += ("social_core.backends.keycloak.KeycloakOAuth2",)

SOCIAL_AUTH_KEYCLOAK_KEY = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_KEY', '')
SOCIAL_AUTH_KEYCLOAK_SECRET = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_SECRET', '')
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY', '')
SOCIAL_AUTH_KEYCLOAK_ALGORITHM = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_ALGORITHM', '')
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL', '')
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = os.environ.get('WEBLATE_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL', '')
```

If this could be backport in a 3.8-x docker image it would be awesome.

Thanks for the tips and/or help.

**Comment by nijel** [comment]
The settings for Docker are now in main Weblate repo: https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py

**Comment by mleneveut** [comment]
it seems to already be in master : https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py#L303

Could you tell me if it is there in 3.8-5 ? The tag 3.8 doesn't include that file.

**Comment by mleneveut** [comment]
ok, found it, sorry for the time wasted.

Cheers.

https://github.com/WeblateOrg/docker/blob/3.8-5/etc/weblate/settings.py#L287

**Comment by nijel** [comment]
I've added it to the docs, it was missing there.
