### ISSUE TITLE
LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH on docker

### ISSUE THREAD

**Issue by schybbkoh** [WeblateOrg/docker#517]
Does the docker version of Weblate respect `LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH` env? While I may be mistaken, so far it would seem it does not.

If so, how should one approach turning the limit off on docker?

**Comment by nijel** [comment]
Currently, it's not there, patches are welcome.

You can always use [configuration override](https://docs.weblate.org/en/latest/admin/install/docker.html#custom-configuration-files).

**Comment by schybbkoh** [comment]
Configuration override worked fine. Since I don't feel confident in meddling with what seem to me a well-organised Python code, this time I'll skip on contributing. Thanks!
