### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by Tharit** [WeblateOrg/docker#52]
I have been running weblate via docker on osx for a while over the past months; I now wanted to set up an instance on a mac mini.
Unfortunately, it seems that the latest version of the containers no longer works.
They start, the log shows no errors, but there are no open ports, and I can not access weblate.

After running into these issues I tried the new current version on my macbook (where it was working before) => same problem.

Am I missing some new configuration options, or is there something else that I could try?

**Comment by Tharit** [comment]
For completeness, here is the output of a fresh installation:

docker-compose up
Creating network "weblatedocker_default" with the default driver
Pulling cache (memcached:1.5-alpine)...
1.5-alpine: Pulling from library/memcached
88286f41530e: Pull complete
0fc4fb72c09d: Pull complete
1e38f9e0675f: Pull complete
a80cc17f2245: Pull complete
0badae89f3cf: Pull complete
Digest: sha256:180e34da7dee18fcd5dee0ef3335a2e844481ed232c84df8f970b2abf89b67e6
Status: Downloaded newer image for memcached:1.5-alpine
Pulling database (postgres:9.6-alpine)...
9.6-alpine: Pulling from library/postgres
019300c8a437: Pull complete
1b9e338691a6: Pull complete
d376e6c136f7: Pull complete
78af63d10e8d: Pull complete
5dfeed4f401b: Pull complete
e75bea9722d2: Pull complete
964036777293: Pull complete
9a9e654cc027: Pull complete
3049bea4ed37: Pull complete
Digest: sha256:5fd73de311d304caeb4f907d4f559d322805abc622e4baf5788c6a079ee5224e
Status: Downloaded newer image for postgres:9.6-alpine
Pulling weblate (weblate/weblate:latest)...
latest: Pulling from weblate/weblate
06b22ddb1913: Pull complete
e2b44f1cf135: Pull complete
e8238350e3dd: Pull complete
136be185538a: Pull complete
f2209cd0daf3: Pull complete
a76178e5608f: Pull complete
f2cc50168d4b: Pull complete
f8f54285a423: Pull complete
caa5daaefec2: Pull complete
04c7b7e004a8: Pull complete
08e24590f4e5: Pull complete
Digest: sha256:84534bdbf37fb714cc06a08bcc454218abf501e53c2022aae519ffcd041cd33c
Status: Downloaded newer image for weblate/weblate:latest
Creating weblatedocker_cache_1 ...
Creating weblatedocker_database_1 ...
Creating weblatedocker_database_1
Creating weblatedocker_database_1 ... done
Creating weblatedocker_weblate_1 ...
Creating weblatedocker_weblate_1 ... done
Attaching to weblatedocker_cache_1, weblatedocker_database_1, weblatedocker_weblate_1
database_1  | LOG:  database system was shut down at 2017-08-14 14:31:23 UTC
database_1  | LOG:  MultiXact member wraparound protections are now enabled
weblate_1   | Postgres is up
database_1  | LOG:  database system is ready to accept connections
database_1  | LOG:  autovacuum launcher started
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, admin, auth, authtoken, contenttypes, gitexport, lang, permissions, screenshots, sessions, sites, social_django, trans
weblate_1   | Running migrations:
weblate_1   |   Applying accounts.0032_auto_20170605_2025... OK
weblate_1   |   Applying permissions.0008_auto_20170605_2025... OK
weblate_1   |   Applying trans.0089_auto_20170713_0946... OK
weblate_1   |   Applying trans.0090_auto_20170718_0857... OK
weblate_1   |   Applying trans.0091_auto_20170719_1612... OK
weblate_1   |   Applying trans.0092_auto_20170719_1616... OK
weblate_1   |   Applying trans.0093_remove_project_push_on_commit... OK
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/search.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/README.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/LICENSE'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/icon-no.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/inlines.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/calendar.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/jquery.init.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/core.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/actions.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/inlines.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/cancel.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/collapse.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/prepopulate.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/actions.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/urlify.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/timeparse.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/SelectBox.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/change_form.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/collapse.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/popup_response.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/dashboard.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/fonts.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/base.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/rtl.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/forms.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/login.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/widgets.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/css/changelists.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/fonts/README.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/img/grid.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/bootstrap.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/jquery-1.12.4.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/ajax-form.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/csrf.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/default.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/prettify-min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/js/coreapi-0.1.0.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/css/default.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/css/bootstrap-tweaks.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/css/prettify.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/css/bootstrap.min.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.eot'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.ttf'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff2'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/img/favicon.ico'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/img/grid.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/js/api.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/js/bootstrap.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/js/jquery-1.10.2.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/js/jquery.json-view.min.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/js/highlight.pack.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/base.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/jquery.json-view.min.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/highlight.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/bootstrap-theme.min.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/bootstrap.min.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/css/font-awesome-4.0.3.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.eot'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.eot'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.ttf'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.ttf'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff2'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/loader-bootstrap.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/favicon.ico'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/chartist.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/style-bootstrap.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/weblate-32.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/weblate-128.png'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/robots.txt'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/multi-select.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-linux/font-linux.eot'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-linux/font-linux.woff'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-linux/font-linux.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-linux/font-linux.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-linux/font-linux.ttf'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/autosize.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/jquery-1.12.4.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/mousetrap.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/mousetrap-global-bind.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/jquery.sortElements.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/js.cookie.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/jquery.multi-select.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/js/chartist.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/config.json'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/js/bootstrap.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/js/bootstrap-datepicker.js'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/css/bootstrap-theme.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/css/bootstrap.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/css/bootstrap-rtl.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/bootstrap/css/bootstrap-datepicker3.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/css/font-awesome.css'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/fonts/fontawesome-webfont.woff2'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/fonts/fontawesome-webfont.svg'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/fonts/fontawesome-webfont.eot'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/fonts/fontawesome-webfont.ttf'
weblate_1   | Copying '/usr/local/lib/python2.7/dist-packages/weblate/static/font-awesome/fonts/fontawesome-webfont.woff'
weblate_1   |
weblate_1   | 136 static files copied to '/app/data/static'.
weblate_1   | Creating user admin
weblate_1   | /usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
weblate_1   |   'Supervisord is running as root and it is searching '
weblate_1   | 2017-08-14 14:33:02,563 CRIT Supervisor running as root (no user in config file)
weblate_1   | 2017-08-14 14:33:02,563 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
weblate_1   | 2017-08-14 14:33:02,573 INFO RPC interface 'supervisor' initialized
weblate_1   | 2017-08-14 14:33:02,573 CRIT Server 'unix_http_server' running without any HTTP authentication checking
weblate_1   | 2017-08-14 14:33:02,574 INFO supervisord started with pid 1
weblate_1   | 2017-08-14 14:33:03,580 INFO spawned: 'nginx' with pid 59
weblate_1   | 2017-08-14 14:33:03,582 INFO spawned: 'uwsgi' with pid 60
weblate_1   | 2017-08-14 14:33:03,590 DEBG 'uwsgi' stderr output:
weblate_1   | [uWSGI] getting INI configuration from /usr/share/uwsgi/conf/default.ini
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,590 DEBG 'uwsgi' stderr output:
weblate_1   | [uWSGI] getting INI configuration from /etc/uwsgi/apps-enabled/weblate.ini
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,598 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139705349024152 for <Subprocess at 139705349322080 with name nginx in state STARTING> (stderr)>
weblate_1   | 2017-08-14 14:33:03,607 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - *** Starting uWSGI 2.0.14-debian (64bit) on [Mon Aug 14 14:33:03 2017] ***
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,608 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - compiled with version: 6.2.1 20161124 on 07 December 2016 16:14:59
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,608 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - os: Linux-4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,609 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - nodename: 1aafedee6079
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,609 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - machine: x86_64
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,609 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - clock source: unix
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,610 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - pcre jit disabled
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,610 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - detected number of CPU cores: 2
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,610 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - current working directory: /
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,611 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - writing pidfile to /run/uwsgi/app/weblate/pid
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,611 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - detected binary path: /usr/bin/uwsgi-core
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,611 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - setgid() to 1000
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,613 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - setuid() to 1000
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,613 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - your memory page size is 4096 bytes
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,613 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - detected max file descriptor number: 1048576
weblate_1   | Mon Aug 14 14:33:03 2017 - lock engine: pthread robust mutexes
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,614 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - thunder lock: disabled (you can enable it with --thunder-lock)
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,618 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/weblate/socket fd 3
weblate_1   | Mon Aug 14 14:33:03 2017 - Python version: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,623 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - Python main interpreter initialized at 0x55d32fcd9e90
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,623 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - python threads support enabled
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,623 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - your server socket listen backlog is limited to 100 connections
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,623 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - your mercy for graceful operations on workers is 60 seconds
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,624 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - mapped 230592 bytes (225 KB) for 2 cores
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,624 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - *** Operational MODE: preforking ***
weblate_1   |
weblate_1   | 2017-08-14 14:33:03,625 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:03 2017 - added /usr/local/lib/python2.7/dist-packages/ to pythonpath.
weblate_1   |
weblate_1   | 2017-08-14 14:33:04,430 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:04 2017 - WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55d32fcd9e90 pid: 60 (default app)
weblate_1   |
weblate_1   | 2017-08-14 14:33:04,431 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:04 2017 - *** uWSGI is running in multiple interpreter mode ***
weblate_1   |
weblate_1   | 2017-08-14 14:33:04,431 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:04 2017 - spawned uWSGI master process (pid: 60)
weblate_1   |
weblate_1   | 2017-08-14 14:33:04,433 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:04 2017 - spawned uWSGI worker 1 (pid: 74, cores: 1)
weblate_1   |
weblate_1   | 2017-08-14 14:33:04,435 DEBG 'uwsgi' stderr output:
weblate_1   | Mon Aug 14 14:33:04 2017 - spawned uWSGI worker 2 (pid: 75, cores: 1)
weblate_1   |
weblate_1   | 2017-08-14 14:33:05,437 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
weblate_1   | 2017-08-14 14:33:05,437 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by nijel** [comment]
It seems that everything is running fine in the container. The weblate container should listed on port 80, have you tried to connect to it?

Previously there was separate nginx based container and now everything is in one container, see https://blog.cihar.com/archives/2017/08/04/changes-docker-container-weblate/

**Comment by Tharit** [comment]
Turns out that I had to add the port mapping manually to the docker-compose.yml - now I can access the instance again. This was not required with the old version, and is not mentioned in the docs, but maybe I should have checked for something like this sooner.
Thanks!

**Comment by nijel** [comment]
What port mapping? I'd like to improve the docs :-)

**Comment by Tharit** [comment]
Sure, should have included that in my previous answer of course.
I had to add the "ports" section to the config, as follows, to make the instance accessible on the host machine:
```
version: '2'
services:
  weblate:
    ports:
      - 80:80
```

**Comment by nijel** [comment]
True, this was not intentionally removed while doing other changes in 77a19ab1c58569aa8537800ca6808b3c85c13d80.
