### ISSUE TITLE
settings.py / Docker environment variables

### ISSUE THREAD

**Issue by lackaff** [WeblateOrg/docker#57]
Question from a Docker newbie: how do I set the variables in settings.py that aren't available as Docker environment variables? Specifically, I need to disable the SIMPLIFY_LANGUAGES settings, but I'm not sure how to access the settings.py file in a Docker deployment.

**Comment by nijel** [comment]
Currently this is not possible without changing the docker image.

**Comment by lackaff** [comment]
Flailing in the dark here, but would enabling the option this just be adding something like this to the docker/settings.py:

```
# Simplify Languages
SIMPLIFY_LANGUAGES = os.environ.get('WEBLATE_SIMPLIFY_LANGUAGES', '0') == '1'
```
Is there a reason (aside from lack of demand/ developer time) that all the settings.py variables are not exposed as docker environment settings?

**Comment by nijel** [comment]
The biggest reason being that nobody has asked for this so far ;-).

**Comment by lackaff** [comment]
Awesome, thanks! I've updated the master and docker branches on my deployment, and attempted to set WEBLATE_SIMPLIFY_LANGUAGES in my docker-compose-https.override.yml file. I've tried setting with both:

`      - WEBLATE_SIMPLIFY_LANGUAGES=False` and
`      - WEBLATE_SIMPLIFY_LANGUAGES=0`

but I am still getting an error when attempting to add a new component that uses extended language codes:

> Multiple translations were mapped to a single language code (no). You should disable SIMPLIFY_LANGUAGES to prevent Weblate mapping similar languages to one.

I've updated and rebuilt the docker images, and have tried a clean docker-compose "down" and "up" after modifying the override file.

**Comment by nijel** [comment]
The change was present in edge images only, I've just pushed it as stable to docker hub.

**Comment by lackaff** [comment]
Many thanks @nijel, working well now!

**Comment by chteuchteu** [comment]
@nijel Hi there! Sorry to dig an old issue (but I'd rather dig a very related old one than opening a new one - or should I?) - we would like to override the `LOGIN_REQUIRED_URLS_EXCEPTIONS` from a Docker environment variable...

I guess that it wouldn't be as easy to implement as `WEBLATE_SIMPLIFY_LANGUAGES` since it's an array (of regexes)

**Comment by nijel** [comment]
Just to update current status - you can override any of Weblate settings using `/app/data/settings-override.py`, see https://docs.weblate.org/en/latest/admin/deployments.html#further-configuration-customization.
