### ISSUE TITLE
Set SSH fingerprints manually

### ISSUE THREAD

**Issue by Vektrat** [WeblateOrg/docker#59]
Hello,

As you know, ssh fingerprints for known_hosts need to be configured via the django admin panel in Weblate, which apparently is pointing at /app/data/ssh.

Is there any setting currently to set those externally to Weblate for automated environments? I've tried to CP files to this path with Docker, but apparently they keep getting removed on application execution (by Weblate itself?).

Maybe this issue would make more sense in Weblate (not Docker), but since you are the same author I'll put it here for now.

Thanks again for this project

**Comment by nijel** [comment]
They are not being removed by Weblate. Maybe you're copying them to wrong location as /app/data is separate volume in docker-compose?
