### ISSUE TITLE
E-Mail: SMTP AUTH extension not supported by server

### ISSUE THREAD

**Issue by Sytm** [WeblateOrg/docker#653]
I was trying to set up Weblate using Docker (behind a Nginx TLS termination proxy) and the connection via the webinterface worked flawlessly, but Weblate wouldn't send emails for invitations and such.

So when I clicked `Send Test E-Mail` in the webinterface I got the error message `SMTP AUTH extension not supported by server`. Could it be that some dependencies are missing in the Docker image or is my SMTP server just not set up correctly?

I also tried appending a specific port number to the host, but that didn't work at all

**Comment by nijel** [comment]
Most likely it's miscofigured mail. See https://docs.weblate.org/en/latest/admin/install/docker.html#email-server-setup

My guess would be that WEBLATE_EMAIL_USE_TLS or WEBLATE_EMAIL_USE_SSL should be set.

**Comment by Sytm** [comment]
Ah, thank you. Looks like I missed that page while looking through the docs. I am going to try this when I'll be at home again

**Comment by Sytm** [comment]
When I put this into my docker-compose.override.yml file:
```
WEBLATE_EMAIL_USE_SSL: "true"
```
Then I get the following error:
```
EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True. 
```
But if I use 
```
WEBLATE_EMAIL_USE_TLS: "true"
```
I get the same error (`SMTP AUTH extension not supported by server`)

**Comment by nijel** [comment]
It depends on what port you use and how your SMTP server is configured...

**Comment by Sytm** [comment]
So I tried a lot of variations of `_TLS`, `_SSL`, differend ports and different SMTP servers and I gave up. Nothing special happend, expect nothing. I give up.

But thank you for trying to help me

**Comment by okainov** [comment]
To whoever stumbles upon the same issue - seems like the proper solution is posted here https://github.com/WeblateOrg/weblate/issues/2502#issuecomment-731227342.

One need to set env var `WEBLATE_EMAIL_PORT=587` **in addition** to `WEBLATE_EMAIL_USE_TLS=True`. Without setting the port it doesn't work for some reason.

**Comment by nijel** [comment]
The port defaults to 25. I've changed it to use more reasonable defaults if SSL/TLS is configured in https://github.com/WeblateOrg/weblate/commit/9b3d75965442c556499f9de6ce275b793a2fbb62
