### ISSUE TITLE
Postgres is unavailable in QNAP Container Station install

### ISSUE THREAD

**Issue by JohnyFW** [WeblateOrg/docker#66]
hello, we are trying to install your weblate docker image on a QNAP device, in the specialized application that this provider has available (Container Station). We select your docker image for Weblate and install correctly. The problem is that when the image starts, it tells us the error message "Postgres is unavailable - sleeping" and the Weblate service does not work.
Would you tell us how to correct the problem?

**Comment by gamalkamal** [comment]
Could you provide container console output ?

**Comment by JohnyFW** [comment]
finally, we have installed from scratch and we have been able to install, the installation manual "is hell"

**Comment by nijel** [comment]
I guess you didn't use docker-compose, but installed just the weblate container. The docs is quite specific on this: https://docs.weblate.org/en/latest/admin/deployments.html#docker
