### ISSUE TITLE
Allow to run only certain services in the container

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/docker#683]
Currently, the number of uwsgi and Celery workers is hardcoded in the image. It is tuned to fit the most usual case, but it can be never ideal for all. Current numbers do not fit small installations (it consumes more memory than needed) and might limit bigger sites.

Desired solution:

* Use some templating language to generate uwsgi and Celery (supervisor) configujrations
* Expose number of workers per celery queue and uwsgi via environment variables
* This will also allow to run uwsgi only nodes or split Celery workers into more nodes (note this currently requires shared filesystem which supports flock based locking)

**Comment by nijel** [comment]
The number of Celery workers can be now tweaked using https://github.com/WeblateOrg/docker/pull/745

What is still missing is number of uwsgi workers and option to disable starting some services. Maybe it would be better to allow running all services standalone without supervisor. That would be more Docker like approach.

**Comment by paulpach** [comment]
#748 should take care of the uwsgi workers option.
