### ISSUE TITLE
Translating issues

### ISSUE THREAD

**Issue by thecraftman** [WeblateOrg/docker#687]
I  am hosting Weblate locally with docker & docker-compose. I ran the docker commands and it worked. I can access weblate from localhost. The issue here is i can't translate from one language to another.  

when i try to add translated languages i can't see other languages. even when adding projects i can't specify the language for it to be translated to. it outputs the error `nothing to list here` . 

is there a workflow for  translation using docker-compose ?

Thanks

**Comment by nijel** [comment]
The languages are based to whatever is in your VCS repository, you can add languages in Weblate as well, see https://docs.weblate.org/en/latest/formats.html#adding-new-translations

**Comment by thecraftman** [comment]
When i try specifying it on the project file it says nothing found.

**Comment by thecraftman** [comment]
Okay, i get this as the error message `Could not fetch the repository: fatal: repository 'https://github.com/thecraftman/experimental-weblate/tree/staging/' not found (128)`

yes i have looked at the documentation i followed it,  I have created the new project. Adding the translation component is the issue

**Comment by thecraftman** [comment]
Thanks, i got it fixed and working

**Comment by thecraftman** [comment]
The issue now i'm having is i am trying to Setting up Weblate to create pull requests and integrate it with github when configuring i get this error when filling the filemask format 
 `The filemask did not match any files. Path of files to translate relative to repository root, use * instead of language code, for example: po/*.po or locale/*/LC_MESSAGES/django.po.`

**Comment by SMotaal** [comment]
@nijel I think it helps to give a little more context:

- The translation workflow we are trying for is to translate all `md` files from a single repo and use a locale-appended path for the translated files in a pull request.

- The documentation seem to centre around using translation strings, however our use case does not use or need such intermediaries, unless Weblate cannot produce the translated `md` files directly.

- What we're aiming for here is a frictionless translation workflow for open source projects to afford equal-opportunity documentation, where all project assets are almost immediately translated and offered in as many languages as needed by contributors.

- What we're hoping for in the future is more inclusive workflows where content committed against any language would afford equal priority and conflict resolution to all members.

It would help if there were existing sample projects that do not involve other platforms and simply operate on the `md`-to-`md` translation workflow.

**Comment by nijel** [comment]
Weblate currently doesn't support directly translating Mardown documents, see https://github.com/WeblateOrg/weblate/issues/3106. You can use po4a to generate PO files from Markdown, translate these in Weblate and let po4a generate the translated Markdown files.

**Comment by thecraftman** [comment]
Okay, Thanks
