### ISSUE TITLE
Update to 2.19

### ISSUE THREAD

**Issue by DiV666** [WeblateOrg/docker#69]
Hi,

How can i update docker weblate to v2.19?

I need fix this problem https://github.com/WeblateOrg/weblate/issues/1666

Can i fix manually?

Thanks,

**Comment by nijel** [comment]
2.19 is not yet released (it's scheduled to end of January). However the fix for  WeblateOrg/weblate#1666 was already part of 2.18...

**Comment by DiV666** [comment]
Sorry,

How can i update weblate/docker to 2.18?

If I do `docker exec <conainer> weblate list_versions` I see `Weblate 2.17.1` and if I do `docker-compose pull`, the console launches `Status: Image is up to date for weblate / weblate: latest`

**Comment by Zemistr** [comment]
@DiV666 Try `weblate/weblate:edge` ;)
I see that latest released version is `2.17.1-2`

https://hub.docker.com/r/weblate/weblate/tags/

**Comment by nijel** [comment]
Apparently I forgot to create the 2.18 tag, I've done that just now, sorry for that...
