### ISSUE TITLE
Add OAuth2 generic authentication

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/docker#698]
Hi, I've got my own OAuth2 provider and I'd like to use it with Weblate.

I've seen that you currently support a wide number of OAuth2 providers and I guess that the framework used probably supports a generic one.

I'm not fluent with the framework, otherwise I'd do a PR.

Thanks

**Comment by nijel** [comment]
I don't think that python-social-auth (library we use for authentication) supports this without writing code for such provider.
