### ISSUE TITLE
Endless redirection when running behind SSL termination load balancer

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/docker#699]
Hi, I'm using Weblate behind an SSL termination load balancer. If I enable `WEBLATE_ENABLE_HTTPS` the site enters in an endless loop that I could only fix by setting `SECURE_SSL_REDIRECT = False`.

The load balancer is configured to forward the following header: `http-request set-header X-Forwarded-Proto https if { ssl_fc }`.

Is this the expected behavior? or am I missing something?

(Thank you for the quick support throughout the issues and PR)

**Comment by nijel** [comment]
The proper fix should be to configure SECURE_PROXY_SSL_HEADER, see https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-SECURE_SSL_REDIRECT

**Comment by lyz-code** [comment]
Thanks for the tip. When setting the header I had the problem that another downstream load balancer was interfering with the header and switching it back to http. If anyone is reading this, use another heade such as `X-Custom-Forwarded-Proto`.
