### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by PhieF** [WeblateOrg/docker#711]
Hi !

I'm trying to recreate a weblate instance but it stucks here

weblate_1   | Creating user admin
weblate_1   | Generating a RSA private key
weblate_1   | ......................................................................................+++++
weblate_1   | .............................................................................................................................................+++++
weblate_1   | writing new private key to '/app/data/ssl/saml.key'
weblate_1   | -----
weblate_1   | You are about to be asked to enter information that will be incorporated
weblate_1   | into your certificate request.
weblate_1   | What you are about to enter is what is called a Distinguished Name or a DN.
weblate_1   | There are quite a few fields but you can leave some blank
weblate_1   | For some fields there will be a default value,
weblate_1   | If you enter '.', the field will be left blank.
weblate_1   | -----
weblate_1   | Country Name (2 letter code) [AU]:problems making Certificate Request

Any ideas ?

Thank you !

**Comment by nijel** [comment]
For the record, this should be fixed by c9146fdc6b810e914bee9bd922b349ad58021c37.
