### ISSUE TITLE
Mapping AD groups to Weblate groups

### ISSUE THREAD

**Issue by azuron** [WeblateOrg/docker#713]
Hello! I configure LDAPS authorization and mapping of AD groups to Weblate groups. Created the "translators" group in AD and Weblate. Added my user to the "translators" group. I need my user to log in to Weblate and get into the translators group in Weblate.  The code looks like this:
```
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType

AUTH_LDAP_BIND_DN = "CN=ldap,CN=Users,DC=example,DC=com"
AUTH_LDAP_BIND_PASSWORD = "password"

# User and group search objects and types
AUTH_LDAP_USER_SEARCH = LDAPSearch("CN=Users,DC=example,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")

# Make selected group a superuser in Weblate
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    # is_superuser means user has all permissions
    "translators": "CN=translators,OU=Groups,DC=example,DC=com",
}

# Map groups from AD to Weblate
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=Groups,DC=example,DC=com", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()
AUTH_LDAP_FIND_GROUP_PERMS = True
```
When logging in to Weblate with a domain account, my user falls into the Users and Viewers groups, but does not fall into the "translators" group. What might be the problem?

**Comment by nijel** [comment]
AUTH_LDAP_USER_FLAGS_BY_GROUP defines flags such as is_superuser, not group membership.

**Comment by azuron** [comment]
I understand, what other flags are there besides is_superuser?

**Comment by nijel** [comment]
There is also is_active

**Comment by nijel** [comment]
If you want to manage group membership, then [AUTH_LDAP_GROUP_SEARCH](https://django-auth-ldap.readthedocs.io/en/latest/reference.html#std:setting-AUTH_LDAP_GROUP_SEARCH) is the right option for you.

**Comment by azuron** [comment]
Checked setting the "is_superuser" flag for my user, everything works. 
I have OU=weblate, it includes the "translators" group and my user is added to this group.
Full path ```my_user -> CN=translators,OU=weblate,OU=Groups,DC=example,DC=com```

When logging in to Weblate, I don't see the "translators"group.
I tried created the "translators" group in Weblate, but my user's username does not add it to the "translators" group in Weblate. Here is an example of my code:
```
# Map groups from AD to Weblate
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=weblate,OU=Groups,DC=example,DC=com", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()
AUTH_LDAP_FIND_GROUP_PERMS = True
```
Tell me where I made a mistake?

**Comment by azuron** [comment]
Tried to do as in Django documentation https://django-auth-ldap.readthedocs.io/en/latest/example.html#example-configuration
To get my group "translators" as CN.
But that doesn't work. Groups do not appear in Weblate.
```
# Set up the basic group parameters.
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "OU=weblate,OU=Groups,DC=example,DC=com",
    ldap.SCOPE_SUBTREE,
    "(objectClass=groupOfNames)",
)
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")

# This is the default, but I like to be explicit.
AUTH_LDAP_ALWAYS_UPDATE_USER = True

# Use LDAP group membership to calculate group permissions.
AUTH_LDAP_FIND_GROUP_PERMS = True

# Cache distinguished names and group memberships for an hour to minimize
# LDAP traffic.
AUTH_LDAP_CACHE_TIMEOUT = 3600
```

**Comment by nijel** [comment]
If you want to create groups, configure AUTH_LDAP_MIRROR_GROUPS or AUTH_LDAP_MIRROR_GROUPS_EXCEPT, the default behavior is only to adjust membership to existing groups (because you will typically have more groups in LDAP than you want to use in Weblate).

**Comment by azuron** [comment]
Thank you very much for your help! The option ```AUTH_LDAP_MIRROR_GROUPS = True``` helped.
