### ISSUE TITLE
How to set SECURE_HSTS_INCLUDE_SUBDOMAINS

### ISSUE THREAD

**Issue by JulianGro** [WeblateOrg/docker#715]
I am getting a warning for not setting SECURE_HSTS_INCLUDE_SUBDOMAINS to true.
The only place in the docs that mentions this is https://docs.weblate.org/en/weblate-4.1.1/admin/sample.html?highlight=SECURE_HSTS_INCLUDE_SUBDOMAINS#sample-configuration
The django docs do also mention this: https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-SECURE_HSTS_INCLUDE_SUBDOMAINS

Grep does not find an option either:
```
root@Vircadia-Weblate-Docker:/var/lib/docker/volumes# grep -r "SECURE_HSTS_INCLUDE_SUBDOMAINS" *
weblate-docker_weblate-data/_data/backups/settings.py:SECURE_HSTS_INCLUDE_SUBDOMAINS = False
root@Vircadia-Weblate-Docker:/var/lib/docker/volumes#

root@Vircadia-Weblate-Docker:~/weblate-docker# grep -r "SECURE_HSTS_INCLUDE_SUBDOMAINS" *
root@Vircadia-Weblate-Docker:~/weblate-docker# 
```

I am now lost on where to set this option.

**Comment by nijel** [comment]
It can be overriden in settings, see https://docs.weblate.org/en/latest/admin/install/docker.html#custom-configuration-files

For upcoming releases this will be automatically enabled with https as that is what most people want anyay, see https://github.com/WeblateOrg/weblate/commit/e5ea20143e03a46986abedb0d383d32bb17d0bea
