### ISSUE TITLE
Github "hub" configuration

### ISSUE THREAD

**Issue by adhyans** [WeblateOrg/docker#726]
- I was just going through the code and saw that there is a code to initialize configuration for Gitlab here https://github.com/WeblateOrg/docker/blob/master/start#L62 , when the docker container is run.

- Is there any specific reason for Github "hub" configuration not being initialized when the docker container is run?

**Comment by nijel** [comment]
The major reason is that nobody has implemented that.

Long term Weblate should use API instead of these CLI tools, but that's not yet on the roadmap, see https://github.com/WeblateOrg/weblate/issues/3493

**Comment by nijel** [comment]
Closing in favor of https://github.com/WeblateOrg/weblate/pull/4224 - we will get rid of using hub/lab tools and use the respective API directly.
