### ISSUE TITLE
Override LOGIN_REQUIRED_URLS_EXCEPTIONS for Docker

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/docker#75]
See https://github.com/WeblateOrg/docker/issues/57#issuecomment-376791774 by @chteuchteu:

> @nijel Hi there! Sorry to dig an old issue (but I'd rather dig a very related old one than opening a new one - or should I?) - we would like to override the `LOGIN_REQUIRED_URLS_EXCEPTIONS` from a Docker environment variable...
>
> I guess that it wouldn't be as easy to implement as `WEBLATE_SIMPLIFY_LANGUAGES` since it's an array (of regexes)

**Comment by nijel** [comment]
@chteuchteu please avoid hijacking resolved issues for unrelated topics.

Handling lists is certainly possible as well, there is already helper for that - `get_env_list`. Anyway what are you trying to achieve?

**Comment by chteuchteu** [comment]
> @chteuchteu please avoid hijacking resolved issues for unrelated topics.

@nijel Sorry about this...

I was trying to set the `LOGIN_REQUIRED_URLS_EXCEPTIONS` parameter from docker's configuration file. We finally created a settings.py file that gets mounted in docker's file system

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
