### ISSUE TITLE
Add options for adding the legal support

### ISSUE THREAD

**Issue by pc-jedi** [WeblateOrg/docker#76]
It would be nice to have an option to enable the weblate.legal.
https://github.com/WeblateOrg/weblate/issues/1968

**Comment by nijel** [comment]
You really want to customize the legal documents prior to use, so it's not that straightforward.

**Comment by Braintelligence** [comment]
What I don't understand is why Weblate doesn't allow to just create custom links in the navbar, so you can set them to an external site with an imprint and privacy notes.

**Comment by nijel** [comment]
Because nobody has contributed patch for this so far :-).

**Comment by Braintelligence** [comment]
Touché. Sadly this wasn't included in the legal module as a low-hanging-fruit solution :(.

**Comment by nijel** [comment]
I don't think you want use legal module just to add footer links. Better to implement such feature in the core.
