### ISSUE TITLE
400 (connection already closed) error when upload soon after download

### ISSUE THREAD

**Issue by li-dl** [WeblateOrg/docker#786]
Actual behaviour: A `wlc download` followed soon after by a `wlc upload` results in a 400 error, but re-attempt the same upload and it succeeds.
Expected behaviour: The first upload should succeed.

I first saw this when using the [Weblate plugin for Serge](https://github.com/dragosv/serge-plugins) (`serge pull-ts` and `serge push-ts`), but I can also reproduce it using `wlc` directly:

```
$ wlc download --output "mycomponent.po" myproject/mycomponent/de
$ wlc upload --overwrite --input "mycomponent.po" --method replace myproject/mycomponent/de
Error: HTTP error 400: Bad Request
$ wlc upload --overwrite --input "mycomponent.po" --method replace myproject/mycomponent/de
```

(The second upload succeeds.)

When using the API directly, I see:

```
$ curl -H "Authorization: Token xxx" --output mycomponent.po  http://weblateserver/api/translations/myproject/mycomponent/de/file/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  378k  100  378k    0     0  3028k      0 --:--:-- --:--:-- --:--:-- 3028k
$ curl -i -H "Authorization: Token xxx" -F file=@mycomponent.po  http://weblateserver/api/translations/myproject/mycomponent/de/file/
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Server: nginx/1.14.2
Date: Tue, 18 Aug 2020 08:03:49 GMT
Content-Type: application/json
Content-Length: 53
Connection: keep-alive
Vary: Accept, Cookie
Allow: GET, POST, PUT, HEAD, OPTIONS
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4701
X-RateLimit-Reset: 39
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: same-origin
Set-Cookie: sessionid=xlrl89r0td61hf1bkohx3uss8hjv9vvu; expires=Tue, 18 Aug 2020 08:40:29 GMT; HttpOnly; Max-Age=2200; Path=/; SameSite=Lax

{"result":false,"detail":"connection already closed"}
```

wlc 1.5 and curl 7.68.0 running on Ubuntu 20.04.1.

```
$ docker-compose exec weblate weblate list_versions
 * Weblate: 4.1.1
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.1
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.6
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.14
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 1.4.6
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-42-generic (x86_64)
```

```
$ docker-compose exec --user weblate weblate weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 111] Connection refused), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#out-mail
?: (weblate.E017) Correct the site domain
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#production-site

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html

System check identified 8 issues (1 silenced).
```

**Comment by li-dl** [comment]
My `docker-compose.yml` file is based on https://github.com/WeblateOrg/docker-compose/blob/master/docker-compose.yml

```
version: "3"
services:
  weblate:
    image: weblate/weblate:4.1.1-2
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    ports:
      - "80:8080"

  database:
    image: postgres:11.8-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:5.0.9-alpine3.12
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

**Comment by nijel** [comment]
Can you please check server logs for detailed error?

**Comment by li-dl** [comment]
> Can you please check server logs for detailed error?

The attached Log1.txt shows a successful `wlc download` followed by a failing `wlc upload`. The part around the error is:

```
weblate_1   | uwsgi stderr | [pid: 559|app: 0|req: 1631/3256] 10.1.112.210 () {38 vars in 555 bytes} [Tue Aug 18 22:55:53 2020] GET /api/translations/myproject/mycomponent/de/ => generated 3272 bytes in 34 msecs (HTTP/1.1 200) 12 headers in 470 bytes (2 switches on core 0)
weblate_1   | uwsgi stderr | 
weblate_1   | uwsgi stderr | WARNING Upload error: InterfaceError: connection already closed
weblate_1   | uwsgi stderr | 
weblate_1   | nginx stdout | 10.1.112.210 - - [18/Aug/2020:22:55:53 +0000] "POST /api/translations/myproject/mycomponent/de/file/ HTTP/1.1" 400 53 "-" "wlc/1.5"
weblate_1   | nginx stdout | 
weblate_1   | uwsgi stderr | [pid: 558|app: 0|req: 1573/3257] 10.1.112.210 () {42 vars in 746 bytes} [Tue Aug 18 22:55:53 2020] POST /api/translations/myproject/mycomponent/de/file/ => generated 53 bytes in 114 msecs (HTTP/1.1 400) 12 headers in 480 bytes (1 switches on core 0)
```

[Log1.txt](https://github.com/WeblateOrg/docker/files/5093216/Log1.txt)

**Comment by nijel** [comment]
The similar issue was reported in https://github.com/WeblateOrg/weblate/issues/3942, but was not really resolved there.

Are there any log entries from the PostgreSQL container in the same time?

**Comment by nijel** [comment]
Also, it might be worth trying Weblate 4.2 which was released yesterday to see if that improves situation (there are no specific fixes for this, but some of the dependency updates might fix this issue).

**Comment by li-dl** [comment]
By the way, I forgot to mention in the intial report that the error does not occur every time, but it doesn't take many attempts to reproduce it.

> Are there any log entries from the PostgreSQL container in the same time?

No, all the entries in the few seconds leading up to the error are from the weblate_1 container. Mostly uwsgi and nginx, with a few celery-main.

> Also, it might be worth trying Weblate 4.2 which was released yesterday to see if that improves situation

I pruned the existing Docker volumes and changed `docker-compose.yml` to use `image: weblate/weblate:4.2-1` and re-tested and I was still able to reproduce the error.

**Comment by nijel** [comment]
I still cannot reproduce this, I have no clue what might be different.

Can you please try enabling connections logging on PostgreSQL to see if it did disconnect? Following should do the trick:

```yaml
services:
  database:
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=true", "-c", "log_disconnections=true", "-c", "log_min_messages=INFO"]
```

**Comment by li-dl** [comment]
A couple more things I've noticed after some more testing:
* With 4.1.1-2, I used to be able to reproduce the issue multiple times in one session. With 4.2-1, I've only been able to reproduce the issue once after each `docker-compose up`.
* I can only reproduce the issue if I'm uploading a .po file that has many strings in it. (The file I'm testing with has over 1,600 strings and is nearly 300kB.) I can't reproduce the issue if I'm uploading the default .po file that only has header lines in it. (I've only tried the header-only .po file in 4.2-1, not 4.1.1-2.)

> Can you please try enabling connections logging on PostgreSQL to see if it did disconnect?

[Log2.txt](https://github.com/WeblateOrg/docker/files/5100005/Log2.txt) has the extra logging enabled, showing everything from container startup through:
```
$ wlc download --output mycomponent.po myproject/mycomponent/de
$ cp mycomponent-withtranslations.po mycomponent.po
$ wlc upload --overwrite --input mycomponent.po --method replace myproject/mycomponent/de
Error: HTTP error 400: Bad Request
```

Should we be worried about this line?
```
weblate_1   | uwsgi stderr | Thu Aug 20 00:31:07 2020 -  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
```

**Comment by nijel** [comment]
> I can only reproduce the issue if I'm uploading a .po file that has many strings in it. 

That sounds like the PostgreSQL server closes the connection when it is idle for too long (while Weblate is parsing the file). Does the PostgreSQL have set `idle_in_transaction_session_timeout`?

> Log2.txt has the extra logging enabled, showing everything from container startup through...

It doesn't seem to contain any of the uwsgi requests, maybe it ends too early?

> WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers

Probably no, harakiri kills requests which take longer than hour, I guess you are nowhere near this limit... Anyway it's not really needed, I've just removed that option.

**Comment by li-dl** [comment]
Is there any other information I can collect that might help?

**Comment by nijel** [comment]
Did you try enabling more verbose logging in PostgreSQL as described in https://github.com/WeblateOrg/docker/issues/786#issuecomment-675950515? It might give a hint why the connection was closed by the server.

**Comment by li-dl** [comment]
> Did you try enabling more verbose logging in PostgreSQL

It was enabled in the log attached to [comment 676833025](https://github.com/WeblateOrg/docker/issues/786#issuecomment-676833025), but since the end of that log was probably truncated, I re-did it for you. This time I documented the steps too...

I'm using:
* A physical Windows 10 host running VirtualBox 6.1.12 and wlc.
* An Ubuntu 20.04.1 VM guest ("weblatevm") running Docker / Weblate.

On the Ubuntu guest:
```
$ git remote --verbose
origin	https://github.com/WeblateOrg/docker-compose.git (fetch)
origin	https://github.com/WeblateOrg/docker-compose.git (push)

$ git pull
Already up to date.

$ git log -1 --oneline
8f5340b (HEAD -> master, origin/master, origin/HEAD) Bump pre-commit from 2.6.0 to 2.7.1

$ cat docker-compose.override.yml 
version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_SITE_DOMAIN: weblatevm
      WEBLATE_ADMIN_PASSWORD: password
      WEBLATE_ADMIN_EMAIL: admin@example.com
  database:
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=true", "-c", "log_disconnections=true", "-c", "log_min_messages=INFO"]

$ docker system prune --volumes
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all volumes not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B

$ docker-compose up
```

On the Windows host machine:
* Zip `mycomponent.pot` into `mycomponent.zip`.
* Open http://weblatevm:80/ in the browser:
    * Sign in.
    * Copy the API key from `Profile -> Settings -> API access` to the `.weblate` config file.
    * `Add -> Add new translation project`:
        * `Project name: MyProject`
        * `Project slug: myproject`
        * `Project website: https://example.com`
        * `Save`
    * `Add new translation component`:
        * `Upload translation files`
        * `Zip file: mycomponent.zip` (see above)
        * `Continue`
        * `Specify configuration manually`
        * `Continue`
        * `File format: gettext PO file`
        * `Filemask: *.po`
        * `Template for new translations: mycomponent.pot`
        * `Save`
    * `mycomponent -> Start new translation`:
        * `German (de)`
        * `Start new translation`

On the Windows host:
```
$ wlc --version
wlc 1.5

$ cat .weblate
[weblate]
url = http://weblatevm/api/

[keys]
http://weblatevm/api/ = rqtpSUzqcTppdfOkHsBbPFe5OqybsiijQJgapCA8

$ wlc download --output mycomponent.po myproject/mycomponent/de

$ wlc upload --overwrite --input mycomponent.translated.po --method replace myproject/mycomponent/de
Error: HTTP error 400: Bad Request
```

Unfortunately, I can't give you the `.pot` or `.po` files used in this test. I tried making new files that I would be able to, but I wasn't able to reproduce the issue with them. I'm still not sure if it's the size of the files that make a difference, or something to do with the contents. For the record, the `mycomponent.translated.po` used above is 386KB and has 1,644 strings.

After the `wlc download` and `wlc upload`, I loaded then force re-loaded http://weblatevm:80/ in the browser, then did `docker-compose down`, just to be double sure that the logs had flushed.

The new log file is: [Log3.txt](https://github.com/WeblateOrg/docker/files/5165889/Log3.txt)
(I've removed the early lines, to keep the size down.)

**Comment by nijel** [comment]
Digging through the log, I think the problematic connection is logged with PID 1760:

```
database_1  | 2020-09-03 02:49:57.600 UTC [1760] LOG:  statement: BEGIN
database_1  | 2020-09-03 02:49:57.600 UTC [1760] LOG:  statement: SELECT (1) AS "a" FROM "trans_unit" WHERE ("trans_unit"."translation_id" = 2 AND "trans_unit"."pending") LIMIT 1
database_1  | 2020-09-03 02:49:57.601 UTC [1760] LOG:  statement: COMMIT
...
database_1  | 2020-09-03 02:50:03.352 UTC [1760] LOG:  disconnection: session time: 0:00:05.769 user=weblate database=weblate host=192.168.192.4 port=51852
```

It seems to match what the file upload is supposed to do prior the traceback and it matches the time of the failed request:

```
weblate_1   | uwsgi stderr | [pid: 621|app: 0|req: 13/31] 10.1.112.210 () {42 vars in 752 bytes} [Thu Sep  3 02:50:03 2020] POST /api/translations/myproject/mycomponent/de/file/ => generated 53 bytes in 70 msecs (HTTP/1.1 400) 12 headers in 480 bytes (2 switches on core 0)
```

The question is why the connection was closed. It was idle for five seconds, but that should not be reason for either side to close it.

I can't reproduce this behavior even with bigger files (I've tried with [Weblate PO files](https://github.com/WeblateOrg/weblate/tree/master/weblate/locale)).

Maybe there is some issue in your Docker networking? Any special setup there? See for example https://stackoverflow.com/questions/43311004/docker-services-stops-communicating-after-some-time, https://github.com/docker/for-mac/issues/2406 or https://github.com/moby/moby/issues/31208

**Comment by li-dl** [comment]
> I'm using:
> * A physical Windows 10 host running VirtualBox 6.1.12 and wlc.
> * An Ubuntu 20.04.1 VM guest ("weblatevm") running Docker / Weblate.

I've ruled out VirtualBox as a possible cause. I can still reproduce the issue using:
* A physical Windows 10 machine running wlc.
* A physical Ubuntu 20.04.1 machine running Docker / Weblate.


> Maybe there is some issue in your Docker networking? Any special setup there?

I'm not specifying any options to `docker-compose up`. Apart from `docker-compose.yml` and `docker-compose.override.yml`, is there somewhere else that network settings might come from?

Does this information help?

```
$ docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
b9ae692348fc        bridge                bridge              local
4fa59288aef5        host                  host                local
3b6ceea83c63        none                  null                local
9aaf0801a859        weblatetest_default   bridge              local

$ docker network inspect bridge host none weblatetest_default
[
    {
        "Name": "bridge",
        "Id": "b9ae692348fc88c73cadc5db8983f8a988c64503e955c61b79c8572b9ea4fa53",
        "Created": "2020-09-05T18:24:52.87270325+10:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    },
    {
        "Name": "host",
        "Id": "4fa59288aef5f5e3a969d4a2ac0f48e403aa3958eafdc08ac34b27f058e96db7",
        "Created": "2020-09-05T18:22:28.388157026+10:00",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    },
    {
        "Name": "none",
        "Id": "3b6ceea83c63ff776bf1985a75e4a3f8dd4b3173909f71e98d46a15d8244b0fd",
        "Created": "2020-09-05T18:22:28.372745391+10:00",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    },
    {
        "Name": "weblatetest_default",
        "Id": "9aaf0801a859ac3ea371e0ec4a287b900a7775234e56db4d5648ab2e23b87ee6",
        "Created": "2020-09-05T18:51:23.074563718+10:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "10e732404938c501253e7177f1e4a6824548667a5bd66d773501fa0117c32fdc": {
                "Name": "weblatetest_cache_1",
                "EndpointID": "5b93de60a32e89705a2f98707788094542f7b610e28ae71da2c56fdac318851c",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "c6b17fbe610aef9b79dd6ec77d6006af03d7addfcc587ec914d0db7c4d7f0ee7": {
                "Name": "weblatetest_weblate_1",
                "EndpointID": "2a49a86a44023bf42ba01dab299d5cdd8366d50b7060acb2274f77fe7e2378ba",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "fd14eca0d5d781130f3cfe4624ff795daf0c94ea26f5519acf3ed653b39686b0": {
                "Name": "weblatetest_database_1",
                "EndpointID": "e75d4454952321b60a715ed9ed474a15e010495c7500fc3040256ef45dbeda79",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "weblatetest",
            "com.docker.compose.version": "1.26.2"
        }
    }
]
```

**Comment by nijel** [comment]
I have no deeper Docker knowledge, so that's not something where I could help. You might try dumping the postgresql traffic by wireshark or tcpdump to see what causes that connection is being closed prematurely. Also, the problematic connection is between Weblate and PostgreSQL, the wlc triggers it only by triggering operation that takes long on Weblate side.

**Comment by Daniel-Tr** [comment]
Hi! I think we are facing a similar (or the same) issue, even though we get an HTTP response of 500, but for the same exception. It just happens randomly during uploads or downloads of translations for us.

Did you see this thread on SO? It sounds like an explanation for this behavior to me:
https://stackoverflow.com/questions/31504591/interfaceerror-connection-already-closed-using-django-celery-scrapy

**Comment by humphrey** [comment]
I get the same issue, with a very similar stack trace in my own custom django project (not using weblate).  I do not yet have a solution, but the issue only occurs when I use `uwsgi`.  If I use `manage.py runserver` it does not occur.
