### ISSUE TITLE
logging to stdout

### ISSUE THREAD

**Issue by tnextday** [WeblateOrg/docker#79]
Outputting logs to stdout and stderr is better in Docker.

**Comment by nijel** [comment]
Patches welcome, I have no clue how to do that easily in our setup (supervisor + uwsgi running Weblate).

**Comment by nijel** [comment]
Just for the reference following log files are currently used:

* `/var/log/syslog` (though syslog) contains Weblate application logs
* `/var/log/nginx/error.log` contains nginx error log
* `/var/log/nginx/access.log` contains nginx access log
* `/var/log/uwsgi/app/weblate.log` contains uswgi log

**Comment by tnextday** [comment]
OK, i will create a PR later.

**Comment by DarrenV79** [comment]
@nijel thanks for the log dir info.  I couldn't find this anywhere but makes sense because I was looking for a weblate directory

FWIW as long as I can configure where the logs go its all good.  These will get pushed for us to an ELK stack anyway since few people will ever log into this instance.

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/docker/pull/81
