### ISSUE TITLE
google translate MT v3 api doesnt have support in settings_docker.py

### ISSUE THREAD

**Issue by atifrizwan89** [WeblateOrg/docker#826]
google translate MT v3 api doesnt have support in settings_docker.py

After adding this code in settings_docker.py, i can get it to work

MT_GOOGLE_CREDENTIALS = os.environ.get("WEBLATE_MT_GOOGLE_CREDENTIALS", None)
MT_GOOGLE_PROJECT = os.environ.get("WEBLATE_MT_GOOGLE_PROJECT", None)
if MT_GOOGLE_CREDENTIALS:
    MT_SERVICES += ("weblate.machinery.googlev3.GoogleV3Translation",)

Can we get this in the docker image??

**Comment by nijel** [comment]
Sure, patches are welcome. AFAIR the credentials is a file, so it would be great to cover this in the documentation.

**Comment by graebertshiva** [comment]
Hi Nijel,

We have upgraded weblate to weblate:4.3.2-1 with the docker image(weblate/weblate:4.3.2-1) and we are using below setting in template for Google API v3 but Still we are unable to get this service reflected in weblate.

{
                    "Name": "WEBLATE_MT_GOOGLE_CREDENTIALS",
                    "Value": "/app/data/file.json"
                },
				{
                    "Name": "WEBLATE_MT_GOOGLE_PROJECT",
                    "Value": "experimentswithcloudservices"
                },
can you please help us to enable this service.

**Comment by nijel** [comment]
As you can see, this issue is not resolved, so nobody has implemented support for these settings. Either submit a patch with that or use custom configuration and add a Python snippet with it...
