### ISSUE TITLE
Add Apertium-APy machine translation

### ISSUE THREAD

**Issue by blizarazu** [WeblateOrg/docker#827]
**Is your feature request related to a problem? Please describe.**
There is no way to activate Apertium-APy machine translation in docker containers.

**Describe the solution you'd like**
Adding the WEBLATE_MT_APERTIUM_APY docker environment variable wich would add the MT_APERTIUM_APY configuration to settings.py file.

**Comment by nijel** [comment]
Patches are welcome. Settings code is here: https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_docker.py and documentation here: https://github.com/WeblateOrg/weblate/blob/master/docs/admin/install/docker.rst

**Comment by nijel** [comment]
Thanks for the patch, fixed via https://github.com/WeblateOrg/weblate/pull/4561
