### ISSUE TITLE
Google login stopped working after upgrading to v4.2.2

### ISSUE THREAD

**Issue by thelinuxer** [WeblateOrg/docker#832]
**Describe the issue**

I installed weblate using docker on a kubernetes cluster a while back and configured it to be able to login with Google and it was working fine. Last night I upgraded to version 4.2.2, password authentication is working fine but Google login is not working and it keeps returning user message whenever I try to login saying " The server does not allow authentication."
I configured the following environment variables:

- WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
- WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
- WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS
- WEBLATE_REQUIRE_LOGIN: 1
- WEBLATE_REGISTRATION_OPEN: 0

**To Reproduce**

I am not sure I have a scenario since I am not sure if it's a bug or a misconfiguration.

**Server configuration and status**
weblate list_versions
 * Weblate: 4.2.2
 * Django: 3.1.1
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.1.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.63
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5.1
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 4.0.14
 * PostgreSQL server: 9.6.19
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://redis-weblate-master:6379/1, redis://redis-weblate-master:6379/1, regular
 * Platform: Linux 4.19.112+ (x86_64)

**Weblate deploy checks**
weblate check --deploy
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/backup.html

**Comment by nijel** [comment]
It might be related to https://github.com/WeblateOrg/weblate/issues/4565. Can you please check the network requests in your browser if that includes correct callback URL while authenticating?

**Comment by thelinuxer** [comment]
@nijel I checked the browser's network tab and found out there's a call that returns 401 status code.
```json
{
     "POST":{
          "scheme":"https",
          "host":"play.google.com",
          "filename":"/log",
          "query":{"format":"json","hasfast":"true"},
          "remote":{"Address":"216.58.205.206:443"}
     }
}
```

**Comment by drzraf** [comment]
I'd like to reopen. I'm suffering the same behavior in a slightly different scenario. I lost my docker install (db and fs). I could restore the database (pg_dump), but afterwards, Google auth doesn't work anymore.
I found a `/app/data/secret` file which has probably been auto-(re)generated. I'm now with the hypothesis that the Google auth could depends on some filesystem secret/hash/salt and that restoring only the database would have left something broken anyway.
