### ISSUE TITLE
Adding WEBLATE_CLIENT_MAX_BODY_SIZE: 100M to override config

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/docker#861]
**Describe the bug**

**WEBLATE_CLIENT_MAX_BODY_SIZE: 100M**
Adding this key to **docker-compose.override.yml** does not seem to change the max allowed file size for uploads on a docker installation.

**To Reproduce**

1. Add/Change key in **docker-compose.override.yml**
2. **Restart** weblate docker container

**Server configuration and status**

weblate docker v 4.2.2

**Comment by nijel** [comment]
There is no such setting documented in https://docs.weblate.org/en/latest/admin/install/docker.html

This parameter is currently hardcoded:

https://github.com/WeblateOrg/docker/blob/70194574f95ce9a9843161482611758e664ee767/etc/nginx/default.tpl#L4

**Comment by nijel** [comment]
PS: The https-portal container recommeded for SSL termination accepts CLIENT_MAX_BODY_SIZE, see https://github.com/SteveLTN/https-portal#configure-nginx-through-environment-variables

**Comment by ilocit** [comment]
OK. So it means that the https-portal "blocks" the larger files and I need to find and change the settings there. Thanks!

**Comment by nijel** [comment]
The setting is used in example docker-compose file:

https://github.com/WeblateOrg/docker-compose/blob/ffcfb3a0549a428c4339ef4a58ef57c6305e2f9e/docker-compose-https.yml#L38

**Comment by ilocit** [comment]
Done. Works not. Thanks for this!

**Comment by Bubu** [comment]
I just wanted to leave a note here that we are easily hitting this hardcoded 100M limit now when uploading project backup archives from another instance. (I'm rebuilding the docker container for another reason anyway, so this isn't a problem right now, but it would be nice if this was configurable from an env var)
