### ISSUE TITLE
EXPOSE Ports not compatible with Cloud Foundry as platform

### ISSUE THREAD

**Issue by sebastianhaeni** [WeblateOrg/docker#863]
The Dockerfile contains `EXPOSE 8080 8443`. This makes this Docker image unusable to be deployed on Cloud Foundry since Cloud Foundry only allows one port to be exposed.

See https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#port_config

Unfortunately I cannot override `EXPOSE` (to my understanding and research).

See:

* https://github.com/moby/moby/issues/2210
* https://github.com/moby/moby/issues/3465

Thus I have to clone this respository and change the `Dockerfile` myself and then have to maintain it with future updates.

What I changed in the `Dockerfile` to make it work:
```patch
- EXPOSE 8080 4443
+ EXPOSE 8080
```

**To Reproduce**

1. Try push the image onto Cloud Foundry. 
2. It won't be reachable via HTTP.

**Expected behavior**

Only one port is exposed. Or remove the `EXPOSE` instruction all together.

Or if you know a way to override this behavior to trick Cloud Foundry to pick up the right port, that would be helpful too. (And no, setting the `PORT` env variable anywhere did not help, I tried that).

**Comment by nijel** [comment]
> Or remove the EXPOSE instruction all together.

EXPOSE is needed for some integrations to offer port mapping for the container.
 
Sticking with just 8080 sounds reasonable as that's what most people will use.
