### ISSUE TITLE
Unable to update to 4.3.2-1, timezone issue

### ISSUE THREAD

**Issue by weeblr** [WeblateOrg/docker#881]
**Describe the issue**

Tyring to update Weblate to 4.3.2-1 (through an ansible script, as always). The app does not star with this error:

```
2020-11-11T10:53:53.992080430Z Updating system timezone to UTC
2020-11-11T10:53:53.992574109Z /app/bin/start: 47: /app/bin/start: cannot create /etc/localtime: Permission denied
```

**To Reproduce**

Not sure, I have been running a standard docker-compose with https-portal, pretty much the recommended setup I think, and just updated the docker image tag (was running 4.2.2 until now).

I have WEBLATE_TIME_ZONE: UTC in the docker-compose-htps.yml file, as well as an WEBLATE_TIME_ZONE environment variable; set to UTC as well.

Any idea why this would fail now after so many version updates in the past?

Many thanks

**Comment by weeblr** [comment]
Hi again

Worth mentionning that redeploying (with the same method) Weblate version 4.2.2-1 restores normal operation, the app container starts up normally.

**Comment by nijel** [comment]
That looks strange. The file is created as group writable while building the container:

https://github.com/WeblateOrg/docker/blob/6893cc2b24ece10b4095f7e274c007c1f27199b6/Dockerfile#L160-L162

Also, I don't see anything related in the difference between these two releases: https://github.com/WeblateOrg/docker/compare/4.2.2-1...4.3.2-1

**Comment by weeblr** [comment]
Yes, I checked the code first and could not find anything. Actually, I tried updating because I was having an actual issue using Weblate so as I was able to revert to 4.2.2-1, I am going to ask about my real, pressing problem and leave the Docker update issue for later...

**Comment by weeblr** [comment]
Hi

I don't do any change to the image itself but I run a custom image FROM the standard weblate one which adds a backup system and a few other things. The actual weblates images are untouched.

Thanks for the input, I'll get back to this later and possibly report any finding.
