### ISSUE TITLE
Issue with Celery (maybe realted to this the performance issues with TM and Auto Translate)

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/docker#887]
Increasingly, we see the following message apearing in the Health Report of our weblate installation using Docker:

`The Celery does not process tasks, or is too slow in processing them.`
 
![image](https://user-images.githubusercontent.com/26718215/99799531-20e2e800-2b33-11eb-9ad8-8b7c92aeb400.png)

Maybe the performance issue related to TM and Auto Translation is related to this too?

The documentation does not give any clues to us regarding any remedies.
Maybe there is some help / information you can give us?

Thanks!

**Comment by nijel** [comment]
Just under this table there is list of queues which will give you more insight what part is actually stuck.

But I think it might be related to auto translate being slow on your system for some reason...
