### ISSUE TITLE
Docker Compose file is still version 1

### ISSUE THREAD

**Issue by almereyda** [WeblateOrg/docker#9]
@species and me just discovered a few caveeats due to the changes from docker compose version 1 to version 2:

* http://weblate.readthedocs.io/en/latest/admin/deployments.html#weblate-and-docker `create` can be run after `build`. 
* Virtual networking needs to be explicitly set up and containers need to be attached to desired frontend and backend networks. Note we are using this together with https://github.com/ecobytes/docker-nginx-gen-letsencrypt
* Therefore the config guessing in `settings.py` does not work anymore.

Additionally the changes proposed in https://github.com/nijel/weblate-docker/issues/2#issuecomment-132467239 appear useful for a high-availability setup.
We are going to publish a fork and mybe issue a PR with the neccessary changes.

---

Resources:

* https://docs.docker.com/compose/compose-file/
  * https://github.com/docker/compose/blob/master/docs/compose-file.md
* https://docs.docker.com/compose/networking/
  * https://github.com/docker/compose/blob/master/docs/networking.md
* https://docs.docker.com/compose/link-env-deprecated/

**Comment by nijel** [comment]
PR is definitely welcome, my Docker knowledge is almost zero...

**Comment by nijel** [comment]
Changed by #12 merged.
