### ISSUE TITLE
Could not create directory '/home/weblate/.ssh'

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/docker#95]
It looks like the docker image does not have the folder /home/weblate

When I redeploy the docker image and I try to commit something in the UI,  I get the following error:

> INFO cubica/ui: updating repository
> ERROR cubica/ui: failed to update repository: Could not create directory '/home/weblate/.ssh'.
> GitLab: The project you were looking for could not be found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists. (128)

the workaround for me is to ssh into my image and issue these commands:
```
cd /home
mkdir weblate
chown weblate:weblate weblate
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
