### ISSUE TITLE
whoosh index error 2.17 -> 3.0.1-6 upgrade

### ISSUE THREAD

**Issue by glensc** [WeblateOrg/docker#96]
i think the folder should be nuked similarly to avatar cache fix.

- https://weblate.example.net/translate/group/project/et/?checksum=&offset=&q=Current+session&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=
- https://ptpb.pw/gJII

**Comment by glensc** [comment]
i'll use this solution for now:
- https://github.com/WeblateOrg/weblate/issues/1508#issuecomment-305294234

```
root@communion /srv/weblate# mv data/weblate/whoosh/ data/weblate/whoosh.old/
root@communion /srv/weblate# docker-compose exec weblate weblate update_index
root@communion /srv/weblate# docker-compose exec weblate weblate rebuild_index --all
Processing 0.0%
Processing 9.3%
Processing 18.5%
Processing 27.8%
Processing 37.1%
Processing 46.3%
Processing 55.6%
Processing 64.9%
Processing 74.1%
Processing 83.4%
Processing 92.7%
Operation completed
```

**Comment by nijel** [comment]
It's covered by [ugprade docs](https://docs.weblate.org/en/latest/admin/upgrade.html#upgrading-from-python-2-to-python-3), but the docker container indeed could do this automatically.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
