### ISSUE TITLE
Use custom addins, checks and fixups scripts

### ISSUE THREAD

**Issue by pleonex** [WeblateOrg/docker#97]
In the case of using Weblate with Docker I haven't been able to find a way to use my custom [checks](https://docs.weblate.org/en/latest/admin/checks.html#writing-own-checks) scripts.

I'm not sure how to do that because according to the [documentation](https://docs.weblate.org/en/latest/admin/checks.html#using-custom-modules-and-classes) there are the following options:
* Copy the files to the default Python site-packages. The one from the user's home directory should work also.
* Copy the files to the Weblate installation _weblate/trans/checks/_.
* Create a Python package and install it in your (virtual) environment.
* I haven't tested this option but I guess that adding the directory to the `PYTHONPATH` environment variable should work also.

I think these options won't work in Docker because the Python directory (including Weblate) aren't permanent. They get reset every time we start the image. And I would like to avoid creating my custom Docker image every time I want to add a script.

I don't much about Docker but I have some ideas:
* Mount an external folder as a volume with Weblate customization files like addins, checks and fixups. Then the entrypoint script ("start") will copy from that volume to the Weblate installation or set the PYTHONPATH environment variable to there.

* Create a Python package, add the list of additional packages to install in docker.override.yml and in the entrypoint script ("start"), run `pip install -U pkg1 pkg2`. So we have always the latest version of the scripts. I think we should provide also a way to specify custom PyPi repositories just in case you can't publish your package in the public PyPi repository or you are [testing locally](https://github.com/wolever/pip2pi).

In any case, we will need to make modifications in the _environment_ and _settings.py_ files to modify the`CHECK_LIST` option.

Do you have more ideas? What would you recommend?
I am happy to contribute with a pull request.

**Comment by nijel** [comment]
For settings override there already is `/app/data/settings-override.py`.

What would already work without doing any changes to docker image:

- store custom module under `/app/data/`, for example under `/app/data/python/weblate_customization`
- insert `/app/data/python` into python search path (`sys.path`) in `/app/data/settings-override.py`
- configure addons/checks/fixup in `/app/data/settings-override.py` as `weblate_customization.yourmodule.YourCheck`

The docker image could be prepared for this - create the path including empty `__init__.py` and adding it into `sys.path`. Rest is just matter of documenting this.

**Comment by pleonex** [comment]
Oh, I didn't know about the `settings-override.py` file. I have just tested your steps and it works perfectly! Thanks

As a improvement I think it would be great if these packages can be installed without going inside the container.
It's a bit tricky and could be risky because if you write something wrong in `settings-override.py`, the container will start to crash and you won't be able to access with `docker-compose exec weblate bash`. You would need to modify the files from the mountpoint (in my case at `/var/lib/docker/volumes/docker_weblate-data/_data/settings-override.py`). 

What do you think about adding these two environment variables?
* `ADDITIONAL_PYTHON_PACKAGES` would contain a list of python packages that the _start_ script will try to install and/or update every time.
* `WEBLATE_CHECK_LIST` would contain the list of checks to enable.

This should also help to share Python packages with checks and addins between weblate installations, instead of copying manually the files into `/app/data/python`.

As a reference, these were the steps I did:
```
docker-compose exec weblate bash
mkdir -p /app/data/python/checks
scp -P ssh_port user@server_ip:fileToSend /app/data/python/checks/

apt-get install vim
vim /app/data/settings-override.py

# Add the following lines:
import sys
sys.path.append("/app/data/python")

CHECK_LIST = (
# list of the default checks
    'checks.module.class'
)
# end of file

exit
docker-compose down
docker-compose up
```

Thanks!

**Comment by nijel** [comment]
I'm not really sure installing packages on container start is a good idea - it can easily happen that the installation will fail or there is newer and not compatible module and your so far working container will be dead...

BTW: The `/app/data` is Docker volume, so you can access it from host as well.

**Comment by pleonex** [comment]
Yeah, I agree.

I got with another idea that I have just tested and it seems to work also. I mounted a local directory as a volume. That's allow me to make quick changes without sending files to the container manually or modify the `/var/lib/...` mountpoint with root permissions. I added the following line to my `docker-compose.override.yml` file:

```
    volumes:
      - $PWD/python:/app/data/python
```
I still need to create manually inside the docker container the `settings-override.py` file that it's less likely to change. Only when adding new checks to the `CHECK_LIST` variable. My local folder could be now a git repo where I can track changes in my addins :)

**Comment by nijel** [comment]
Good point, you can probably add the custom settings in a same way.

**Comment by ShadowXVII** [comment]
I'm trying to replicate mounting the local directory as a volume... do you have any more details about the above @pleonex ? Managed to lose my docker volume once :P

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
