### ISSUE TITLE
Set "WEBLATE_SIMPLIFY_LANGUAGES=0" not working

### ISSUE THREAD

**Issue by KarinBerg** [WeblateOrg/docker#98]
I run the weblate image version 3.1.1-6 on a Kubernetes cluster. On the Web-UI, I get the message "Multiple translations were mapped to a single language code (en). You should disable SIMPLIFY_LANGUAGES to prevent Weblate mapping similar languages to one." while saving a new component.

So I followed the given advice and set the "WEBLATE_SIMPLIFY_LANGUAGES" to 0 to disable SIMPLIFY_LANGUAGES. I restarted the Kubernetes pod and tried it again. But still I get the above message. I also verified that the environment variable WEBLATE_SIMPLIFY_LANGUAGES inside the pod is really set to 0.

Could you give me a hint what I do wrong?

**Comment by KarinBerg** [comment]
That's what I also thought :)
Maybe something else goes wrong.
I try to create a weblate component on a repository which contains following language files:
- AppResources.bg-BG.resx
- AppResources.bg.resx
In my understanding because I have a language file without a country specifier I get the message:
"Multiple translations were mapped to a single language code (en). You should disable SIMPLIFY_LANGUAGES to prevent Weblate mapping similar languages to one."
But if I would set WEBLATE_SIMPLIFY_LANGUAGES=0 then this is allowed right?

**Comment by nijel** [comment]
Can you please post whole configuration? The error message is about English (what is assumably source language), but you list Bulgarian.

Anyway: What is reason for having both bg and bg-BG?

**Comment by KarinBerg** [comment]
Ok, the Bulgarian files were just an example. So here is a list of our real translation files:
- AppResources.resx  This is the base language file
- AppResources.en.resx
- AppResources.en-GB.resx
- AppResources.en-IE.resx
- AppResources.en-EN.resx
- AppResources.de.resx
- AppResources.de-DE.resx
- AppResources.de-AT.resx
- AppResources.de-CH.resx
- AppResources.bg-BG.resx
- AppResources.bg.resx
And we need the AppResources.de.resx, AppResources.bg.resx or AppResources.en.resx files as fallback languages for smartphone devices where the language is e.g. "de" but the country is "LU" for Luxemburg. Otherwise those users would get the base language.

After I removed the file "AppResources.en-EN.resx" it seems to work. So want checks do you perform on language files?

**Comment by nijel** [comment]
The problem is that `AppResources.resx` corresponds to English by defaults (depends on your project settings).

**Comment by KarinBerg** [comment]
After removing some dublicated resx files it worked. Thanks for your support.
