### ISSUE TITLE
WARNING overcommit_memory is set to 0!

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/docker#980]
Does this warning affect the performance of weblate in docker?
Performing the recommended solution on the main system does not change anything.
Maybe the changes are to be inside the container?
`cache_1         | 1:M 19 Feb 2021 16:03:06.714 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

**Comment by nijel** [comment]
This comes from redis and setting on system level should address it, see https://github.com/docker-library/redis/issues/165 or https://github.com/docker-library/redis/issues/14 or https://r-future.github.io/post/how-to-fix-redis-warnings-with-docker/

**Comment by tomkolp** [comment]
File modification helped: docker-compose-https.yml
`version: '3'

services:
  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  # Your existing Redis service
  redis:
    image: 'redis'
    restart: 'always'
    depends_on:
      - redis-overcommit`
