### ISSUE TITLE
How to block bots?

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/docker#983]
![Screenshot_20210227-132415~2](https://user-images.githubusercontent.com/39633242/109387200-40429b80-7900-11eb-9f72-7d6760393592.png)
Is it possible to block bots?  They download translations and load the server.  Docker installation.

**Comment by nijel** [comment]
Turns out there is a bug in the Docker container and robots.txt is not served because of that. Having that present should work for well-behaving bots.
