### ISSUE TITLE
Question about Weblate maintenance tasks

### ISSUE THREAD

**Issue by KarinBerg** [WeblateOrg/docker#99]
Hi,
I have a question regarding the maintenance task mentioned here:
https://docs.weblate.org/en/weblate-3.1.1/admin/deployments.html?highlight=WEBLATE_SECRET_KEY#maintenance-tasks

Is it correct that if I use your docker image and run it inside of Kubernetes that the docker image itself runs this cron jobs? Or do I have to trigger them by myself?

**Comment by nijel** [comment]
Yes, in 3.1 it's done by cron, in 3.2 it has been moved to Celery, but in both cases it's done inside the Weblate container.

**Comment by nijel** [comment]
Yes.

**Comment by KarinBerg** [comment]
Perfect! thank you very much :)

**Comment by mleneveut** [comment]
@KarinBerg Can you help us running Weblate in Kubernetes plz ? https://github.com/WeblateOrg/weblate/issues/1205
